// <auto-generated />
using System;
using HRIS.Infrastructure.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRIS.Infrastructure.Migrations
{
    [DbContext(typeof(HRISDbContext))]
    [Migration("20231113065015_AddHRISTables")]
    partial class AddHRISTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRIS.Domain.Models.Entities.Config", b =>
                {
                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Section", "Key");

                    b.ToTable("Configs");

                    b.HasData(
                        new
                        {
                            Section = "SYSTEM",
                            Key = "ID_NUMBER_FORMAT",
                            Value = "{0}-{1}-{2}"
                        },
                        new
                        {
                            Section = "SYSTEM",
                            Key = "ID_NUMBER_DIGIT",
                            Value = "7"
                        },
                        new
                        {
                            Section = "SYSTEM",
                            Key = "ID_NUMBER_EMPPLOYEE_PREFIX",
                            Value = "EMP"
                        });
                });

            modelBuilder.Entity("HRIS.Domain.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72d21fba-3724-47c5-4682-4201c938e103"),
                            BirthDate = new DateTime(2023, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 6, 16, 15, 45, 890, DateTimeKind.Local).AddTicks(2664),
                            CreatedBy = "Woodrow.Hahn79@gmail.com",
                            FirstName = "Jadon",
                            Gender = "Female",
                            LastName = "Walker",
                            MiddleName = "௼䍃﵅儂䜚��凢ݓ",
                            Number = "㨥᤿ꪌ研펢泅⌮欓대ᴖ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b3e3b638-a432-b5d9-7cad-5f7c6b11253b"),
                            BirthDate = new DateTime(2023, 1, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 22, 21, 16, 28, 260, DateTimeKind.Local).AddTicks(1790),
                            CreatedBy = "Nathanael.Nicolas97@gmail.com",
                            FirstName = "Adolfo",
                            Gender = "Male",
                            LastName = "Bahringer",
                            MiddleName = "ଦ䛥鐎엨�淬Ȱﳘ姝",
                            Number = "ᬆ䛆ኇ௺採續಍㽵ᶙ팊",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("69dff5bb-ce1a-3fdc-e4ca-c6ac5c54bac7"),
                            BirthDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 14, 5, 53, 42, 16, DateTimeKind.Local).AddTicks(2455),
                            CreatedBy = "Tyreek_Nader@yahoo.com",
                            FirstName = "Augustus",
                            Gender = "Female",
                            LastName = "Boehm",
                            MiddleName = "꯶ᠯ쭶儏淘㍴ꭙ酤ಃ",
                            Number = "ル摲ည짙ퟜ랤豑䩙",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5e31878a-27dc-bc1e-0ad6-ea5ebfb40e67"),
                            BirthDate = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 5, 17, 37, 33, 167, DateTimeKind.Local).AddTicks(1907),
                            CreatedBy = "Shaun.Lowe8@gmail.com",
                            FirstName = "Dagmar",
                            Gender = "Female",
                            LastName = "Gibson",
                            MiddleName = "胘�뭫龙拆䔱㮣즸",
                            Number = "尽땍㞂盦玩㹆뒸仫쏂",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5a798d23-88e4-cbe1-8b88-7f73d35490f1"),
                            BirthDate = new DateTime(2022, 11, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 16, 9, 14, 27, 114, DateTimeKind.Local).AddTicks(6481),
                            CreatedBy = "Elenor_Davis@yahoo.com",
                            FirstName = "Colten",
                            Gender = "Female",
                            LastName = "Lindgren",
                            MiddleName = "똪講퓹伄စ圵篳말喅㦇",
                            Number = "鮥ⴕ菢쀳侺쩃櫤돸뵛",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3e530cd9-f93e-9ff9-6f5d-703344b2b82b"),
                            BirthDate = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 24, 13, 39, 9, 93, DateTimeKind.Local).AddTicks(8381),
                            CreatedBy = "Cristina_Herzog50@hotmail.com",
                            FirstName = "Bernita",
                            Gender = "Male",
                            LastName = "Lakin",
                            MiddleName = "튊尼謝⎉嘘䃬셎㐟",
                            Number = "룎릙歽鹛챟뱬纺ᐁ덫筂",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6a933246-2ba8-0c10-f44b-c73ae109f6d5"),
                            BirthDate = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 29, 16, 33, 8, 311, DateTimeKind.Local).AddTicks(207),
                            CreatedBy = "Jailyn_Thompson@gmail.com",
                            FirstName = "Obie",
                            Gender = "Male",
                            LastName = "Cruickshank",
                            MiddleName = "摐裫瀘頉�凜冑ꅦ哈짪",
                            Number = "濰䩰嫹仩⽸鞲䦦䢷ퟆ൞",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("1e3fc74a-6fd4-e8fd-afcf-89a1068c6dee"),
                            BirthDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 12, 15, 20, 49, 211, DateTimeKind.Local).AddTicks(5859),
                            CreatedBy = "Gay.Littel@hotmail.com",
                            FirstName = "Eda",
                            Gender = "Male",
                            LastName = "Johnston",
                            MiddleName = "稉㈯땋鋯搒裗첑언嚙",
                            Number = "ᗢᜰ뢞㤔쎪看ᖻ渻",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cbd098f3-04d5-deac-4101-3b057f897bb1"),
                            BirthDate = new DateTime(2023, 10, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 20, 5, 45, 56, 708, DateTimeKind.Local).AddTicks(3990),
                            CreatedBy = "Evelyn_Jenkins@hotmail.com",
                            FirstName = "Katrina",
                            Gender = "Female",
                            LastName = "Purdy",
                            MiddleName = "㝹쿚世ᄛ玚輊⪾呈䪢홳",
                            Number = "㱃쳻襘㧙ᘅ̈፰┻螟뎺",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("38396acc-3fdd-c893-252f-de4c4e3f613d"),
                            BirthDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 29, 22, 17, 25, 973, DateTimeKind.Local).AddTicks(9538),
                            CreatedBy = "Alivia42@yahoo.com",
                            FirstName = "Columbus",
                            Gender = "Female",
                            LastName = "Walker",
                            MiddleName = "歓熛洋弡ⷽŉ⎮濆∘",
                            Number = "꥟ਠ㸱뻝㧎鼇㏞ꧡ䬆촴",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d67ad5e6-8fcc-27f1-ce2b-ecc500183800"),
                            BirthDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 11, 10, 0, 54, 976, DateTimeKind.Local).AddTicks(7733),
                            CreatedBy = "Verda94@yahoo.com",
                            FirstName = "Julio",
                            Gender = "Female",
                            LastName = "Bogisich",
                            MiddleName = "発굲㗬㤱彵棍弌הּ쌋",
                            Number = "崜ꕖ⡢롙孵ꅒ炭䗙幀渜",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("da2d8833-861c-62b8-d029-b108885a1c45"),
                            BirthDate = new DateTime(2023, 5, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 24, 17, 35, 51, 546, DateTimeKind.Local).AddTicks(2861),
                            CreatedBy = "Chadd5@yahoo.com",
                            FirstName = "Casimir",
                            Gender = "Male",
                            LastName = "Nader",
                            MiddleName = "ꓚ璼臭윌䴄葥털빠쯓㡗",
                            Number = "ᡂ煹䕴뒔ꭗ组㭒璶匈่",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("32a7a197-c125-2516-0aed-9532e3302f0c"),
                            BirthDate = new DateTime(2023, 5, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 22, 1, 18, 11, 942, DateTimeKind.Local).AddTicks(1863),
                            CreatedBy = "Sage18@hotmail.com",
                            FirstName = "Dominic",
                            Gender = "Female",
                            LastName = "Tillman",
                            MiddleName = "鷺햸篺撶␃ʐ즮�䥗",
                            Number = "絇꾀㊽놧瀻䭀壪㬘呏ꗇ",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("574bccc4-823b-a038-a0ac-b3b9d1c80095"),
                            BirthDate = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 27, 11, 35, 56, 455, DateTimeKind.Local).AddTicks(8299),
                            CreatedBy = "Johanna31@yahoo.com",
                            FirstName = "Gerry",
                            Gender = "Female",
                            LastName = "Pfannerstill",
                            MiddleName = "�뭤浮갱ﰝ焢䴸苊辂쮫",
                            Number = "⑧铩뚍㌾ﳞ兯魳ﲻ纲ဍ",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0bad8d4e-cf3f-8fef-939a-0f47106cdee4"),
                            BirthDate = new DateTime(2023, 8, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 3, 12, 53, 47, 367, DateTimeKind.Local).AddTicks(2592),
                            CreatedBy = "Camren.Bradtke25@yahoo.com",
                            FirstName = "Ernestina",
                            Gender = "Male",
                            LastName = "Bosco",
                            MiddleName = "౵ꢶ䔌ㄝ杠嚏旀糏欃",
                            Number = "沌ⲓ움뒩산쟇폏昝যد",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("bf8759b8-5935-d3e0-7e85-d87cc47adc1b"),
                            BirthDate = new DateTime(2023, 4, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 25, 12, 0, 49, 527, DateTimeKind.Local).AddTicks(8140),
                            CreatedBy = "Karen78@hotmail.com",
                            FirstName = "Una",
                            Gender = "Male",
                            LastName = "Kovacek",
                            MiddleName = "꾹慁螵闁䷃ꂱ뽤䍐ặ啈",
                            Number = "烴쟠嚨駜䶵䶩뢅倨ힴ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("65f30850-3fae-d256-f585-a844d9123b10"),
                            BirthDate = new DateTime(2023, 4, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 15, 10, 17, 20, 440, DateTimeKind.Local).AddTicks(1358),
                            CreatedBy = "Miller74@yahoo.com",
                            FirstName = "Cornell",
                            Gender = "Male",
                            LastName = "Konopelski",
                            MiddleName = "툒ꢟ☥䭋ሊ⻁ᢞꈟ巴",
                            Number = "锼䎌੥̓䆺៿瘍ݧ﫷䃃",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0d34999f-7057-bb4c-36c6-c98aa1b8ef90"),
                            BirthDate = new DateTime(2023, 11, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 12, 11, 52, 36, 750, DateTimeKind.Local).AddTicks(8912),
                            CreatedBy = "Jordon12@gmail.com",
                            FirstName = "Cleora",
                            Gender = "Female",
                            LastName = "Cummings",
                            MiddleName = "큦뿎脗ྕឤ肤띵밀↪ស",
                            Number = "ꭩʜ瑬ਞჀ柀ꢖ᡼벩˳",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("78b03e07-dc3c-c7aa-a2d3-2650ac577ada"),
                            BirthDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 13, 6, 37, 54, 452, DateTimeKind.Local).AddTicks(272),
                            CreatedBy = "Casimer_Blick@gmail.com",
                            FirstName = "Breanne",
                            Gender = "Female",
                            LastName = "Mueller",
                            MiddleName = "贅炤⺨逻◌�诰⒡溴ꞧ",
                            Number = "⾲荥䘦⦪̍忙謯疐✬",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5bc5b3c7-6104-949b-6151-251c73d9c3c9"),
                            BirthDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 31, 18, 18, 2, 320, DateTimeKind.Local).AddTicks(745),
                            CreatedBy = "Wiley.Watsica@hotmail.com",
                            FirstName = "Elliot",
                            Gender = "Female",
                            LastName = "Wolf",
                            MiddleName = "惣简委촭쬇鬘＾ٳᝦ㉗",
                            Number = "춰뇝怸ἥ䌷❑鷾㹸威",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("66e0d778-d89c-772a-1e12-67cc1ead081a"),
                            BirthDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 10, 9, 32, 55, 186, DateTimeKind.Local).AddTicks(8465),
                            CreatedBy = "Terrance.Rippin23@yahoo.com",
                            FirstName = "Jean",
                            Gender = "Female",
                            LastName = "Klein",
                            MiddleName = "땺윢ᷝ퉰騼澪头匮집",
                            Number = "ꌔ畍⛴ᨣ밑鱠ꮕ壜稑籢",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("64a88f11-09c8-e3d8-0820-0b22e68a4078"),
                            BirthDate = new DateTime(2023, 4, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 6, 18, 4, 0, 66, DateTimeKind.Local).AddTicks(5950),
                            CreatedBy = "Florence_Gaylord70@hotmail.com",
                            FirstName = "May",
                            Gender = "Female",
                            LastName = "Howell",
                            MiddleName = "j缑똌岛杌᱌遢ၪ䶞䲞",
                            Number = "䟎赚罌驲꼥뙟",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("38283774-380f-af82-abb9-120c33206c37"),
                            BirthDate = new DateTime(2023, 5, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 29, 9, 0, 7, 467, DateTimeKind.Local).AddTicks(7051),
                            CreatedBy = "Miller_Bode@gmail.com",
                            FirstName = "Rory",
                            Gender = "Female",
                            LastName = "Zulauf",
                            MiddleName = "뺚ꍅ넷첈륋瘖㙴弨醐⽱",
                            Number = "肒䲢쪗澺롭玽�劣횰",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("1ed16f43-95b9-4756-e664-57a1c93f11d5"),
                            BirthDate = new DateTime(2023, 8, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 10, 14, 54, 51, 736, DateTimeKind.Local).AddTicks(6244),
                            CreatedBy = "Immanuel56@hotmail.com",
                            FirstName = "Makenna",
                            Gender = "Male",
                            LastName = "VonRueden",
                            MiddleName = "꘍ﶚ鳜钯ꈮ鞵�퇺䚠鳍",
                            Number = "罹ⅽ猻杶륄桹騫௄侬蹌",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e1cec46e-e8e7-23b9-18b2-54c0c7d27751"),
                            BirthDate = new DateTime(2022, 12, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 7, 14, 37, 30, 777, DateTimeKind.Local).AddTicks(6766),
                            CreatedBy = "Bridget.King@yahoo.com",
                            FirstName = "Kenyatta",
                            Gender = "Female",
                            LastName = "Trantow",
                            MiddleName = "넚娸❑斯ޕ췽꩘꺽豀",
                            Number = "Ỳ䚌怳肁ᣲˢ뜂�晫ꊟ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3953bc7a-326b-27bd-3d2a-b30a57283cb3"),
                            BirthDate = new DateTime(2023, 10, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 15, 5, 3, 17, 178, DateTimeKind.Local).AddTicks(1506),
                            CreatedBy = "Ralph3@gmail.com",
                            FirstName = "Erick",
                            Gender = "Male",
                            LastName = "Heathcote",
                            MiddleName = "≡ई荮㑩싪俼嗤Ȝᆡ甽",
                            Number = "賤ዼ昐쿏肸숴ᙏ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ca1853ad-3d23-39fa-807a-3a9d7eacef4f"),
                            BirthDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 27, 20, 56, 20, 697, DateTimeKind.Local).AddTicks(7564),
                            CreatedBy = "Janelle29@gmail.com",
                            FirstName = "Jena",
                            Gender = "Female",
                            LastName = "Tromp",
                            MiddleName = "ᡳ滿�﶐읲鶑掲ᅑᇭ反",
                            Number = "᳗蜯锨腵埥댰ゅ諃춲俷",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("69485f87-f8ac-9c92-e60d-bd72aa6df9d3"),
                            BirthDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 6, 23, 22, 49, 739, DateTimeKind.Local).AddTicks(4413),
                            CreatedBy = "Sadye_Gerhold@yahoo.com",
                            FirstName = "Jayde",
                            Gender = "Female",
                            LastName = "Macejkovic",
                            MiddleName = "硾ꘔ㶊欿椉黣姤韑郄꟟",
                            Number = "Ϣ↓臗躄ꠚ뼈℧赽",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("def53f0e-f4ef-cf0d-a273-7b5822350737"),
                            BirthDate = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 25, 17, 14, 44, 119, DateTimeKind.Local).AddTicks(5960),
                            CreatedBy = "Bethany_Powlowski90@gmail.com",
                            FirstName = "Magdalena",
                            Gender = "Male",
                            LastName = "Mann",
                            MiddleName = "ר㖟礩죣顮랠讀脴毧솿",
                            Number = "惡Ꮈ姗눹憅桌羲",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("589ae92a-6f89-b2bd-9864-b397ecb33d6a"),
                            BirthDate = new DateTime(2023, 11, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 28, 16, 50, 37, 919, DateTimeKind.Local).AddTicks(5659),
                            CreatedBy = "Mafalda.Lakin30@hotmail.com",
                            FirstName = "Reuben",
                            Gender = "Female",
                            LastName = "Bashirian",
                            MiddleName = "ꏻ咗린岛萉᪐۱몯",
                            Number = "媬�緤萭ẗ螫擘ෝ",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a2497ba2-0f2f-7755-5f7b-2bf028817fe5"),
                            BirthDate = new DateTime(2023, 6, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 2, 3, 58, 32, 635, DateTimeKind.Local).AddTicks(4835),
                            CreatedBy = "Jameson12@gmail.com",
                            FirstName = "Toby",
                            Gender = "Female",
                            LastName = "Hegmann",
                            MiddleName = "ᘖ↌鼊Ⳍ뛼腨熕蔮녉",
                            Number = "뉩臟ᑯ絭靾䚀뜺粁⧕",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("639d07f3-729a-3099-5af8-48fde6b7b012"),
                            BirthDate = new DateTime(2022, 11, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 6, 0, 40, 29, 735, DateTimeKind.Local).AddTicks(153),
                            CreatedBy = "Jaden_Johns21@gmail.com",
                            FirstName = "Abbey",
                            Gender = "Female",
                            LastName = "Gleichner",
                            MiddleName = "ῢ㏘变⌅妎룽⡕斬勶",
                            Number = "羄슓豋뒅恬ص、ﴤ䜹",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("76895c73-e301-7823-f330-490e9e64e841"),
                            BirthDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 25, 0, 10, 14, 4, DateTimeKind.Local).AddTicks(8540),
                            CreatedBy = "Heloise.Collier3@yahoo.com",
                            FirstName = "Shanon",
                            Gender = "Male",
                            LastName = "Bode",
                            MiddleName = "鈛樤퓤ﭻ엎䊗䕂ꑕ⿞탅",
                            Number = "첳퇣ᦥ郥淾괘喦",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("21027bf0-fd99-5d2b-47a0-a255b2eedc52"),
                            BirthDate = new DateTime(2023, 6, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 9, 0, 17, 43, 875, DateTimeKind.Local).AddTicks(2917),
                            CreatedBy = "Emile59@yahoo.com",
                            FirstName = "Estrella",
                            Gender = "Female",
                            LastName = "Hilll",
                            MiddleName = "瞸㌒侓괩㺝衄ﶪ㎍하",
                            Number = "篗穆ᒓ끠頛焿嚞⩢�",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("96eecc70-9731-e246-48e5-5fd3e81d58c4"),
                            BirthDate = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 14, 14, 20, 29, 198, DateTimeKind.Local).AddTicks(9321),
                            CreatedBy = "Lenora_Breitenberg91@hotmail.com",
                            FirstName = "Earnest",
                            Gender = "Female",
                            LastName = "Terry",
                            MiddleName = "Ɜ㼃愒䋨얬﹥맶Ộ㇥",
                            Number = "黓腣짔汢᭧즯見ウ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f0b16ca0-501f-d402-c9d9-195084137bbd"),
                            BirthDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 17, 13, 27, 53, 683, DateTimeKind.Local).AddTicks(5374),
                            CreatedBy = "Gretchen_Hudson@gmail.com",
                            FirstName = "Diego",
                            Gender = "Female",
                            LastName = "Turner",
                            MiddleName = "揦瞓頔̋직慾屭",
                            Number = "鳋ﺫڙ㒧䦀셲㓒既썗䐁",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9d4580c5-604f-3d51-e300-cd57d32ff547"),
                            BirthDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 14, 23, 41, 38, 814, DateTimeKind.Local).AddTicks(213),
                            CreatedBy = "Hanna.Kshlerin14@yahoo.com",
                            FirstName = "Kurtis",
                            Gender = "Female",
                            LastName = "Beer",
                            MiddleName = "⮾屐脔鏭㥓⯫蓮蹛롖",
                            Number = "ﶻ쁛歸櫴庌얨鹼惻㋻",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e5d720dc-2b8c-6ebc-c848-3458887dd7dd"),
                            BirthDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 14, 4, 53, 4, 146, DateTimeKind.Local).AddTicks(8726),
                            CreatedBy = "Savion_Sipes@gmail.com",
                            FirstName = "Iva",
                            Gender = "Female",
                            LastName = "Hoppe",
                            MiddleName = "삳楩遹꩖艺嘾’맺礡噩",
                            Number = "眷ඇꅸ཈禸Ŗ鷖陁蜈�",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c5cea935-9b55-8d80-4e05-1466538d901f"),
                            BirthDate = new DateTime(2022, 11, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 5, 11, 51, 59, 798, DateTimeKind.Local).AddTicks(262),
                            CreatedBy = "Allene52@yahoo.com",
                            FirstName = "Maida",
                            Gender = "Female",
                            LastName = "Hintz",
                            MiddleName = "ϖ梖厵膃ꖮ愆燴뀗荜팓",
                            Number = "Ꜻ魼ꔭ␷ﮘዒ尽瀝㿧䰑",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4f0d94b7-a3fe-3c0b-a801-6bfb1b4243c2"),
                            BirthDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 2, 20, 22, 19, 444, DateTimeKind.Local).AddTicks(2414),
                            CreatedBy = "Zetta.Carter@hotmail.com",
                            FirstName = "Berneice",
                            Gender = "Male",
                            LastName = "Ankunding",
                            MiddleName = "辚爲錴뾯蔚毦좞ᄧޛ",
                            Number = "걇꘲뫱⭽퐒댑炵褤뉙ో",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ef292764-4e1e-7159-6947-8078c1930e9d"),
                            BirthDate = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 22, 16, 18, 28, 144, DateTimeKind.Local).AddTicks(8209),
                            CreatedBy = "Gayle.Bins4@hotmail.com",
                            FirstName = "Ricardo",
                            Gender = "Male",
                            LastName = "Langworth",
                            MiddleName = "藾尹ᬲ歬஼脶ꐡ봌",
                            Number = "㠬퇋焞㯝裏酏庎ር",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b4d11b30-1c2d-aac5-5a34-2cf401ac0004"),
                            BirthDate = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 9, 5, 3, 59, 800, DateTimeKind.Local).AddTicks(3600),
                            CreatedBy = "Lesley18@gmail.com",
                            FirstName = "Avery",
                            Gender = "Male",
                            LastName = "Nitzsche",
                            MiddleName = "訁�낏烝ن侭긤ƺଡ଼",
                            Number = "识ᵒ蛪潽ⱄ탴ⴘ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("6a8372ab-3a90-33a4-b79e-f47c8d95bdab"),
                            BirthDate = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 5, 21, 21, 36, 398, DateTimeKind.Local).AddTicks(7462),
                            CreatedBy = "Maude_Schuppe@yahoo.com",
                            FirstName = "Adaline",
                            Gender = "Male",
                            LastName = "Ruecker",
                            MiddleName = "턞학娞嬋봩஫뼈爿",
                            Number = "濨㙍뿢햷긺젯᝾ᜭ푲쏒",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ef1b4f0a-dde4-9fde-c1bf-e6dea7688813"),
                            BirthDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 16, 19, 6, 14, 994, DateTimeKind.Local).AddTicks(632),
                            CreatedBy = "Maddison33@hotmail.com",
                            FirstName = "Enos",
                            Gender = "Male",
                            LastName = "Schmitt",
                            MiddleName = "�띎㘎�뇍浒僃뇗䙏",
                            Number = "騂毒门Ⅷ퀍菵뭍떞�豓",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a858d93d-0fbf-7f32-690a-98c355d1cb52"),
                            BirthDate = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 11, 18, 55, 48, 479, DateTimeKind.Local).AddTicks(3538),
                            CreatedBy = "Jessie_Streich44@gmail.com",
                            FirstName = "Maiya",
                            Gender = "Female",
                            LastName = "Steuber",
                            MiddleName = "빸鍝ᯣꥋ̚㝧郐燺蛴憿",
                            Number = "᮴㩇捇殞闒滒먽ﭻ里℡",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f6a1b377-c8d0-bcb5-4af3-9b3f7cac1278"),
                            BirthDate = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 9, 2, 52, 38, 89, DateTimeKind.Local).AddTicks(5892),
                            CreatedBy = "Tanya37@gmail.com",
                            FirstName = "Ashleigh",
                            Gender = "Female",
                            LastName = "Bernhard",
                            MiddleName = "ܖ୼춑Ԥ�悽찷삝",
                            Number = "�꬞퐙ꔆ๫�ܜꮍለ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d9c9994e-d33a-b594-83f7-2b6787668b73"),
                            BirthDate = new DateTime(2022, 12, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 23, 7, 9, 10, 637, DateTimeKind.Local).AddTicks(4811),
                            CreatedBy = "Gwendolyn91@hotmail.com",
                            FirstName = "Katheryn",
                            Gender = "Male",
                            LastName = "Treutel",
                            MiddleName = "�䊵씾ᱴ졗䃷蹕槀獆",
                            Number = "㓙౜㾿멯ℰ䓥悌별Ӧ憎",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("959702e4-5711-c401-6d17-ac21c5d4da60"),
                            BirthDate = new DateTime(2023, 2, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 5, 2, 17, 55, 958, DateTimeKind.Local).AddTicks(1552),
                            CreatedBy = "Gonzalo.Sauer64@yahoo.com",
                            FirstName = "Sidney",
                            Gender = "Male",
                            LastName = "Mayert",
                            MiddleName = "进莨⊟뉲꿮艦͇갵",
                            Number = "跊㾃㭾髄ቀ眾ﳩ̚",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("40ca5130-28cc-223d-74c7-e701d8822520"),
                            BirthDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 25, 3, 28, 55, 661, DateTimeKind.Local).AddTicks(9096),
                            CreatedBy = "Mario_Jenkins@gmail.com",
                            FirstName = "Reba",
                            Gender = "Female",
                            LastName = "Cartwright",
                            MiddleName = "䢖썡赛誇㱠៦穇䭳륵",
                            Number = "ߚŶ텀뇱◒Ἧꔪ�໽푻",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("12eaecf9-7692-c4ff-a401-6a58c11831f9"),
                            BirthDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 3, 8, 23, 15, 705, DateTimeKind.Local).AddTicks(8033),
                            CreatedBy = "Monique85@hotmail.com",
                            FirstName = "Rowena",
                            Gender = "Female",
                            LastName = "DuBuque",
                            MiddleName = "ઓ까࢜꺇湠䚳⦐ᩗօ",
                            Number = "㺯ᐩ鯷䡎䠰䚬慪昁㯮",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1fa5a138-b717-aa73-0d68-8ce08305ad0b"),
                            BirthDate = new DateTime(2023, 1, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 18, 22, 27, 19, 361, DateTimeKind.Local).AddTicks(3559),
                            CreatedBy = "Kadin_Robel96@yahoo.com",
                            FirstName = "Gabriella",
                            Gender = "Male",
                            LastName = "Lebsack",
                            MiddleName = "堲窳ែ᫑鹥祑ヸ踏⾸Ꞣ",
                            Number = "嫡漧ꧪ珁焵﷉ড়缮鴻",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("3be346f9-80b7-1faa-da59-af021c85e9c0"),
                            BirthDate = new DateTime(2023, 4, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 23, 17, 30, 15, 738, DateTimeKind.Local).AddTicks(7623),
                            CreatedBy = "Jimmy.Hilpert@hotmail.com",
                            FirstName = "Anika",
                            Gender = "Male",
                            LastName = "Hilll",
                            MiddleName = "抗诐༂鉄柣媬Ⓓ鸕䑀殷",
                            Number = "߈ἵ䲺돴ಏ뾎운辄䛭",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("09c7536a-1f9c-a250-0f4c-33cbae99ef91"),
                            BirthDate = new DateTime(2022, 12, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 30, 20, 30, 35, 763, DateTimeKind.Local).AddTicks(5719),
                            CreatedBy = "Theresia83@hotmail.com",
                            FirstName = "Granville",
                            Gender = "Female",
                            LastName = "DuBuque",
                            MiddleName = "먆콖䞘ᣡ풣纂穑ᗩᣡ煙",
                            Number = "볒卐�⊮쿃㑬ⶕ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a7046255-59ff-b486-dd53-45dbfdf5d128"),
                            BirthDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 17, 8, 3, 13, 183, DateTimeKind.Local).AddTicks(455),
                            CreatedBy = "Ashlynn79@yahoo.com",
                            FirstName = "Christop",
                            Gender = "Male",
                            LastName = "Herman",
                            MiddleName = "싾᫅쨡닩荷ॊ틌䨕䂖",
                            Number = "聹⿫ダན基�睬鬱公",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bec9aaca-5e97-5bff-143f-1e929902372d"),
                            BirthDate = new DateTime(2023, 10, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 7, 16, 46, 8, 196, DateTimeKind.Local).AddTicks(2617),
                            CreatedBy = "Bud23@yahoo.com",
                            FirstName = "Garnett",
                            Gender = "Male",
                            LastName = "Goldner",
                            MiddleName = "猉⯋룹鎆뽜⏖歔銽䑻㞍",
                            Number = "ꆗ׼䨺ޖꏯ枺쥭핝끨",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("421a72bd-f62e-5651-e95c-5ea44a5efeeb"),
                            BirthDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 3, 14, 59, 45, 268, DateTimeKind.Local).AddTicks(4965),
                            CreatedBy = "Casper_Green70@gmail.com",
                            FirstName = "Kian",
                            Gender = "Female",
                            LastName = "Johnston",
                            MiddleName = "돽믞嗔豎꽲쒊珢왩崊",
                            Number = "ᘅ焲汆ꉦาḔ繻펪皁",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dd3ce7cb-5d3b-1ca6-a1af-86ac08c10978"),
                            BirthDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 6, 13, 5, 51, 961, DateTimeKind.Local).AddTicks(3027),
                            CreatedBy = "Jada91@hotmail.com",
                            FirstName = "Alice",
                            Gender = "Male",
                            LastName = "Rowe",
                            MiddleName = "턷�灾悶嘞摫ቸ諘",
                            Number = "㝇索Ⲥ�蝽㸺鉼氃ڱ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("0c12a4b7-1263-4825-6204-eab83fe2bc9b"),
                            BirthDate = new DateTime(2023, 4, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 7, 7, 52, 30, 898, DateTimeKind.Local).AddTicks(9988),
                            CreatedBy = "Toney.Gibson93@gmail.com",
                            FirstName = "Maurice",
                            Gender = "Female",
                            LastName = "Toy",
                            MiddleName = "쯋盨鲠룡地੻蓅佸䴼䌄",
                            Number = "ࣃ圑㓞躨儱齭ꌸꭉ撪�",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("fb100e8c-5051-7373-b97e-c25202896c8d"),
                            BirthDate = new DateTime(2023, 6, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 17, 21, 40, 26, 756, DateTimeKind.Local).AddTicks(4272),
                            CreatedBy = "Misael_Gulgowski98@yahoo.com",
                            FirstName = "Roxanne",
                            Gender = "Male",
                            LastName = "Bauch",
                            MiddleName = "ꭻဋ䲳䖳打ࣄ媄揘✍",
                            Number = "뽸莰ꊝᡎ誅퓾昬㑔䧹呌",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a7387916-b23a-aef6-d431-0dbf5d9c4198"),
                            BirthDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 29, 14, 45, 31, 797, DateTimeKind.Local).AddTicks(3881),
                            CreatedBy = "Kian_OHara@yahoo.com",
                            FirstName = "Evangeline",
                            Gender = "Male",
                            LastName = "Bechtelar",
                            MiddleName = "欧ަⰺꈾ颍퓺텫ⅺ᩼︣",
                            Number = "᝛焼ቨ๫窖茐﨡郥낊ｹ",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ce058b36-8464-3d72-57e8-3978674a3cc3"),
                            BirthDate = new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 10, 18, 47, 24, 301, DateTimeKind.Local).AddTicks(2906),
                            CreatedBy = "Hildegard.Schaden@hotmail.com",
                            FirstName = "Cameron",
                            Gender = "Female",
                            LastName = "Ortiz",
                            MiddleName = "箑縁ß긱诼ﵒ텞ḃﱏ",
                            Number = "뻺꿁嗭䤩ﰊ泊￁郲ꂕ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7f95f2a9-ac0b-5e14-ea26-20707a3d3ebd"),
                            BirthDate = new DateTime(2023, 1, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 25, 13, 48, 30, 115, DateTimeKind.Local).AddTicks(2084),
                            CreatedBy = "Matilda.Nicolas@hotmail.com",
                            FirstName = "Fleta",
                            Gender = "Female",
                            LastName = "Windler",
                            MiddleName = "癍닮ᒍ쯀质韀䩗⬔",
                            Number = "�뽷拆閟歱賬≰",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("da9f5920-0841-3cfe-289c-283a6cc6d42a"),
                            BirthDate = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 22, 8, 27, 0, 793, DateTimeKind.Local).AddTicks(761),
                            CreatedBy = "Rosendo_Cormier@gmail.com",
                            FirstName = "Melany",
                            Gender = "Female",
                            LastName = "Marks",
                            MiddleName = "㚦鵞퓐兪䪥喏㍸焾᭜欜",
                            Number = "䰠�尣ꖩ轸釥ఞ雅㳇惖",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0f0377ea-06f8-acdd-96cf-f32506761903"),
                            BirthDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 28, 1, 35, 57, 281, DateTimeKind.Local).AddTicks(213),
                            CreatedBy = "Alexa.Dickens8@yahoo.com",
                            FirstName = "Brenden",
                            Gender = "Female",
                            LastName = "Feest",
                            MiddleName = "䠞睓黦욂⾏ᰑ᧧ἲ",
                            Number = "抍睤傹奉칗箈龊梐ッ忇",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b53957f5-593c-342c-0303-f63193d63148"),
                            BirthDate = new DateTime(2022, 11, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 3, 20, 49, 15, 74, DateTimeKind.Local).AddTicks(7997),
                            CreatedBy = "Cali.Emard@hotmail.com",
                            FirstName = "Santino",
                            Gender = "Female",
                            LastName = "Borer",
                            MiddleName = "�粴昲ᱚķ઱㘆剓愝䌺",
                            Number = "羲菴욂솛뵻��볒ᥤ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("67739aec-eb78-9aef-e0a6-9c7aaf6b5af1"),
                            BirthDate = new DateTime(2022, 12, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 28, 15, 33, 31, 496, DateTimeKind.Local).AddTicks(8436),
                            CreatedBy = "Preston39@yahoo.com",
                            FirstName = "Berenice",
                            Gender = "Female",
                            LastName = "Walsh",
                            MiddleName = "浄웹竏鞒衅嬫췜Ꝏ꾷",
                            Number = "늁㝶⊟媍蘙웿氈溂ꐅ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f448a69e-1c80-82d8-3b75-0a35ee74cdba"),
                            BirthDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 13, 3, 17, 26, 383, DateTimeKind.Local).AddTicks(7663),
                            CreatedBy = "Gerald66@gmail.com",
                            FirstName = "Deron",
                            Gender = "Female",
                            LastName = "Strosin",
                            MiddleName = "⊚㾓Ἶᖘﶍ툲ꨢݱ菎ᧅ",
                            Number = "袈혎ﰚ룚㢿♺츠瓃�欚",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("8e2b8823-9a4e-ee54-21ed-d770af98d2ed"),
                            BirthDate = new DateTime(2023, 4, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 28, 14, 40, 31, 448, DateTimeKind.Local).AddTicks(6023),
                            CreatedBy = "Pattie_Wisoky9@yahoo.com",
                            FirstName = "Bert",
                            Gender = "Female",
                            LastName = "King",
                            MiddleName = "풸閼ᑁḼ椩蘢洢诗ūዟ",
                            Number = "⢃尸쏣ﾔ䅫ὖ⋽娐閤",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("245cc7ba-f395-74da-954b-f88ef451b309"),
                            BirthDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 19, 8, 15, 49, 576, DateTimeKind.Local).AddTicks(8903),
                            CreatedBy = "Glenna.Durgan46@gmail.com",
                            FirstName = "Molly",
                            Gender = "Male",
                            LastName = "Stehr",
                            MiddleName = "頧䤊꡿ଂ硲ﾖ睎Ệ듢",
                            Number = "ஶ쟂떣砗ⰉԎ᪃ﻍ४",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5c4e369e-a4de-896f-73bc-70a810107330"),
                            BirthDate = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 20, 11, 51, 40, 52, DateTimeKind.Local).AddTicks(8718),
                            CreatedBy = "Norene.Hermiston@hotmail.com",
                            FirstName = "Natalie",
                            Gender = "Male",
                            LastName = "Muller",
                            MiddleName = "탙岱쌻߉ԇዳ雞᭴㊾塺",
                            Number = "ꔟ솁坖囘帹ᡴ䇁梉溙",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("36c23d42-b626-7db2-b9fb-73b5331bcded"),
                            BirthDate = new DateTime(2023, 3, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 17, 8, 49, 8, 878, DateTimeKind.Local).AddTicks(609),
                            CreatedBy = "Lindsey.Miller@hotmail.com",
                            FirstName = "Richie",
                            Gender = "Male",
                            LastName = "Mayer",
                            MiddleName = "▜枔꫆﹝潢鉛Л᫫૯",
                            Number = "�逡ዥ⺈؁秜౴ﭷ堷",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2891d5d2-4977-3c10-b5fe-3561c031c315"),
                            BirthDate = new DateTime(2023, 2, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 31, 13, 59, 51, 861, DateTimeKind.Local).AddTicks(6115),
                            CreatedBy = "Donny_OHara79@gmail.com",
                            FirstName = "Connie",
                            Gender = "Female",
                            LastName = "Sawayn",
                            MiddleName = "베桴槹﵎§쮞張ᠤꐙ୯",
                            Number = "蟃炷㲯돭汯⹕䗜ᲀ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ad126b3a-af02-1f24-0ae3-143a231d5695"),
                            BirthDate = new DateTime(2023, 8, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 2, 3, 41, 25, 299, DateTimeKind.Local).AddTicks(2912),
                            CreatedBy = "Ara_Grady13@hotmail.com",
                            FirstName = "Alejandra",
                            Gender = "Male",
                            LastName = "Hayes",
                            MiddleName = "㱻䐬�㾊珼舕陝퐹ꠧ",
                            Number = "螃丁廹袾䓖셤ᄾ䯮㗁䢛",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1951e95f-2623-7a93-9ced-14f96258569d"),
                            BirthDate = new DateTime(2023, 3, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 3, 15, 55, 36, 223, DateTimeKind.Local).AddTicks(8332),
                            CreatedBy = "Kamron24@gmail.com",
                            FirstName = "Gladyce",
                            Gender = "Male",
                            LastName = "Abernathy",
                            MiddleName = "ℌ�遟ᅱ癅ࡖ꽏k",
                            Number = "ᆦ墶퉉忂ꯩ䆆剤ⶉ᝶",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("05f7fb9a-bbfd-86a8-2304-99e30984734d"),
                            BirthDate = new DateTime(2023, 7, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 15, 17, 9, 0, 693, DateTimeKind.Local).AddTicks(6632),
                            CreatedBy = "Sylvan47@gmail.com",
                            FirstName = "Casimer",
                            Gender = "Female",
                            LastName = "Abshire",
                            MiddleName = "첐氨壳짥䏳紃岒὚濕췒",
                            Number = "ᣎጂሖ軦췎➱丰᳊ﳁㆳ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("1339bf5f-0178-da1e-adb1-9e4463110821"),
                            BirthDate = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 6, 10, 42, 29, 299, DateTimeKind.Local).AddTicks(4136),
                            CreatedBy = "Jackeline_Walsh30@yahoo.com",
                            FirstName = "Concepcion",
                            Gender = "Male",
                            LastName = "Nicolas",
                            MiddleName = "밎됲욧�쭍丱犥㭠ウ",
                            Number = "�禖ﳬ햪籹汊쿃゚좸㍜",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("307bcba8-846f-364b-c5a2-c769f554ad07"),
                            BirthDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 21, 1, 2, 25, 4, DateTimeKind.Local).AddTicks(2974),
                            CreatedBy = "Marshall22@hotmail.com",
                            FirstName = "William",
                            Gender = "Female",
                            LastName = "Mertz",
                            MiddleName = "㰬걮㈫畠앖璽럌쥐鳿",
                            Number = "ⴐ㙨鲦樒닓萧激忳㳮",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ae48ac6f-f0c2-1fbb-25ca-f18e44d6b72d"),
                            BirthDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 19, 6, 51, 11, 942, DateTimeKind.Local).AddTicks(3443),
                            CreatedBy = "Felipa_Altenwerth99@gmail.com",
                            FirstName = "Maegan",
                            Gender = "Female",
                            LastName = "Ebert",
                            MiddleName = "ꉣﾃ奈�诟茛㪂",
                            Number = "㨬Ⅻ탗嵨ꗰ�팠푹喩̕",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d92cc03c-23a2-7d67-134d-6c96ed87f959"),
                            BirthDate = new DateTime(2023, 5, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 18, 0, 24, 51, 418, DateTimeKind.Local).AddTicks(3459),
                            CreatedBy = "Yesenia_Wyman34@hotmail.com",
                            FirstName = "Nels",
                            Gender = "Male",
                            LastName = "Pfeffer",
                            MiddleName = "杓ᨨሺ硦韟瓸푬",
                            Number = "吘婪從苻ဨ蟪ᣂ巪",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d03fc0fd-11eb-b1bb-c1f9-90c47b501888"),
                            BirthDate = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 2, 7, 27, 9, 40, DateTimeKind.Local).AddTicks(6362),
                            CreatedBy = "Lemuel21@hotmail.com",
                            FirstName = "Erich",
                            Gender = "Male",
                            LastName = "Stokes",
                            MiddleName = "텔ၽ쓹⑄熌会玹㶳",
                            Number = "䤰눀칩㹇묮腧�卮깘筂",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0e62f746-e4fc-b40b-5de9-6c2c45e8f493"),
                            BirthDate = new DateTime(2023, 2, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 11, 2, 11, 58, 818, DateTimeKind.Local).AddTicks(5347),
                            CreatedBy = "Garrison_Terry16@gmail.com",
                            FirstName = "Audrey",
                            Gender = "Female",
                            LastName = "Upton",
                            MiddleName = "訤ꢱ玚脥᳌音떢",
                            Number = "顺绦겞쑔益作茻쇝",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0bad9c90-a898-20f1-28a4-a518958a1390"),
                            BirthDate = new DateTime(2022, 11, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 14, 20, 4, 39, 705, DateTimeKind.Local).AddTicks(3386),
                            CreatedBy = "Daphney_Corwin98@hotmail.com",
                            FirstName = "Rowena",
                            Gender = "Male",
                            LastName = "Hane",
                            MiddleName = "哱ኞ周仉葷롕눿₫뾗",
                            Number = "륥Ჹ៾�╩╹긏옒炙",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("e4372be3-37b8-ae80-f6a5-f0d8e2082631"),
                            BirthDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 19, 10, 20, 57, 866, DateTimeKind.Local).AddTicks(4977),
                            CreatedBy = "Murray22@gmail.com",
                            FirstName = "Leanne",
                            Gender = "Male",
                            LastName = "Carroll",
                            MiddleName = "坬ほ䦡淸㇪ཱི鰷ꀣ⑐",
                            Number = "�ꛪ㉣䭱崙◢禞◓",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("da41e7c8-765a-446e-a68f-6855e41000e6"),
                            BirthDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 28, 21, 27, 31, 29, DateTimeKind.Local).AddTicks(7508),
                            CreatedBy = "Laverne.Nikolaus@gmail.com",
                            FirstName = "Dexter",
                            Gender = "Male",
                            LastName = "Rempel",
                            MiddleName = "�鶏�劌뤻úⅹ啶箛",
                            Number = "䮕❥苃ꊇᱜ軚ͮɒ焽",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("0bccea20-602e-97a0-756d-7596cf597d2b"),
                            BirthDate = new DateTime(2023, 2, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 17, 1, 4, 43, 562, DateTimeKind.Local).AddTicks(2763),
                            CreatedBy = "Shyanne37@gmail.com",
                            FirstName = "Torrey",
                            Gender = "Male",
                            LastName = "Hammes",
                            MiddleName = "�㚔웽蝌엔盙꬯⣨賯ၹ",
                            Number = "짯ғဂ⡣왂䅪⌂ᜂ阁",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("99797dab-1bfb-52c2-d891-3747209def86"),
                            BirthDate = new DateTime(2023, 7, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 12, 22, 45, 36, 862, DateTimeKind.Local).AddTicks(6449),
                            CreatedBy = "Alize13@hotmail.com",
                            FirstName = "Zachary",
                            Gender = "Female",
                            LastName = "Denesik",
                            MiddleName = "狟ꛛ便罖풔덺뵃༔⛆",
                            Number = "惪秞ɂ馸읡᭗꬀ⲷ캫",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3990ba6c-fc61-bc7d-755e-8caa123b49d2"),
                            BirthDate = new DateTime(2023, 7, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 1, 4, 35, 35, 753, DateTimeKind.Local).AddTicks(8651),
                            CreatedBy = "Alessandro_Conroy63@gmail.com",
                            FirstName = "Joe",
                            Gender = "Male",
                            LastName = "Legros",
                            MiddleName = "䇞蝙䊜୪⁺㧠Ꮶ걔掤",
                            Number = "９�驲郇锦⋞鱢䴌�",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4cf57b4c-fa61-8362-7081-697e47a28af8"),
                            BirthDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 15, 5, 42, 27, 52, DateTimeKind.Local).AddTicks(3271),
                            CreatedBy = "Floyd.Marvin@gmail.com",
                            FirstName = "Rusty",
                            Gender = "Male",
                            LastName = "Bogisich",
                            MiddleName = "ꃇ槇䓘秂辶혶습喼쪪꾙",
                            Number = "窎눴㐎ത횫谼ờ芜墸펰",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("82a72215-10a1-8287-8b1a-fd5bed0127da"),
                            BirthDate = new DateTime(2023, 7, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 12, 9, 57, 1, 123, DateTimeKind.Local).AddTicks(3095),
                            CreatedBy = "Graciela3@yahoo.com",
                            FirstName = "Ettie",
                            Gender = "Male",
                            LastName = "Ankunding",
                            MiddleName = "惏磀封竑䍅梛蔎䘫～筝",
                            Number = "⭤䮃�豇겕銋讀ꋥ螞",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c3eadbd8-6984-221d-1c26-291dffc9c3b3"),
                            BirthDate = new DateTime(2023, 10, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 21, 8, 19, 59, 315, DateTimeKind.Local).AddTicks(2979),
                            CreatedBy = "Olen_Romaguera66@hotmail.com",
                            FirstName = "Willa",
                            Gender = "Male",
                            LastName = "Herzog",
                            MiddleName = "ቡր䩸⠪링靾鞌�貇핑",
                            Number = "꺐넚夆狝ꠗ鏏姩�ퟁ퉁",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("2eaf6ee2-3238-4736-740d-2d47632b3508"),
                            BirthDate = new DateTime(2023, 9, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 10, 6, 52, 27, 4, DateTimeKind.Local).AddTicks(8595),
                            CreatedBy = "Laura2@hotmail.com",
                            FirstName = "Lorenza",
                            Gender = "Female",
                            LastName = "Nitzsche",
                            MiddleName = "煶䗐╠Ɠ耺諷낙넵땒㝜",
                            Number = "픏讏攈ﳰ䙺㾣䇕⤞",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("522e4e1a-48ec-b392-7e1b-ebe5f0dba4e3"),
                            BirthDate = new DateTime(2023, 7, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 23, 8, 17, 42, 407, DateTimeKind.Local).AddTicks(6747),
                            CreatedBy = "Cyril18@gmail.com",
                            FirstName = "Lucas",
                            Gender = "Female",
                            LastName = "Schumm",
                            MiddleName = "뚼ꎊ�謏ꎬ亡堿",
                            Number = "⿯㜌Ðḅ達ູ㥀唄㾞",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3250fa3a-fe86-88ab-08c4-9688c3e6b401"),
                            BirthDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 24, 2, 52, 23, 123, DateTimeKind.Local).AddTicks(1647),
                            CreatedBy = "Rafael_Murazik@yahoo.com",
                            FirstName = "Ally",
                            Gender = "Female",
                            LastName = "Zboncak",
                            MiddleName = "鞱ⷮ㼷✭㢏ꀉ咩늁臦䎥",
                            Number = "薢힆넪盟餹彸梔礄",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("8e776fde-df9c-b418-16f1-af78161d9dc8"),
                            BirthDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 16, 9, 15, 39, 979, DateTimeKind.Local).AddTicks(1070),
                            CreatedBy = "Colton_Labadie54@gmail.com",
                            FirstName = "Shawn",
                            Gender = "Male",
                            LastName = "Thompson",
                            MiddleName = "斩鞕⚱蜉�ﰱ鲴꒨ର⭏",
                            Number = "첝頻었ˁ悹꤀醨唂�",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("dc734178-b2bd-9f75-38a8-928cc25ebbe0"),
                            BirthDate = new DateTime(2022, 12, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 13, 10, 23, 44, 868, DateTimeKind.Local).AddTicks(7089),
                            CreatedBy = "Jamie.Botsford46@hotmail.com",
                            FirstName = "Rosalyn",
                            Gender = "Male",
                            LastName = "Trantow",
                            MiddleName = "㿪▋⿿䤠镭䫝㟛沗",
                            Number = "멟ㇳ腊钪㬏㌹⧋꒽뽫",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f864e468-3ef4-37d3-320c-cc1d369dc3b5"),
                            BirthDate = new DateTime(2023, 3, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 24, 5, 36, 9, 780, DateTimeKind.Local).AddTicks(9731),
                            CreatedBy = "Darrell91@yahoo.com",
                            FirstName = "Morgan",
                            Gender = "Male",
                            LastName = "Champlin",
                            MiddleName = "ﲹ鍥䧇廅䧝黬ᄬ춙秢⢩",
                            Number = "ႋ菖쵳᪔㰯Ỻ留蔠",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4104b05f-9fcc-a4cf-89aa-33549f3f567c"),
                            BirthDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 4, 14, 16, 20, 181, DateTimeKind.Local).AddTicks(3883),
                            CreatedBy = "Rowena65@hotmail.com",
                            FirstName = "Don",
                            Gender = "Female",
                            LastName = "Dibbert",
                            MiddleName = "퐰禡惽劕Ꞅ狆㏨函舘ܗ",
                            Number = "坑숱뙈⋗눇眙띪睟⇋",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("bba555f5-1c76-2071-e73a-39ccfe32b969"),
                            BirthDate = new DateTime(2023, 4, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 29, 2, 13, 18, 254, DateTimeKind.Local).AddTicks(6276),
                            CreatedBy = "Werner.Schneider@yahoo.com",
                            FirstName = "Elvie",
                            Gender = "Female",
                            LastName = "Bayer",
                            MiddleName = "砵㘓運窉㤟䪓褌湏⁝",
                            Number = "ꢨ鴉ﺳ܃㶔뉨�汾",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a1f4faee-539c-d0b8-1916-b960394c64a0"),
                            BirthDate = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 10, 1, 38, 39, 367, DateTimeKind.Local).AddTicks(4703),
                            CreatedBy = "Wyatt_Steuber@hotmail.com",
                            FirstName = "Kennith",
                            Gender = "Male",
                            LastName = "Berge",
                            MiddleName = "緊担㘍縅ꂑ蘲Ẏ絓滫屰",
                            Number = "ȱ㜆兄㔾뢓벱닉ኡࣀ鄦",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2bbbee4c-25cd-4de5-5453-547ded6fa41f"),
                            BirthDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 9, 23, 9, 56, 895, DateTimeKind.Local).AddTicks(7161),
                            CreatedBy = "Lavina.Hand@gmail.com",
                            FirstName = "Lester",
                            Gender = "Male",
                            LastName = "O'Kon",
                            MiddleName = "蜌휐휕ﺸ櫓睾鍶ꁋ쬁",
                            Number = "蟣畄ோ螉쾽횠䯐ﯔ䚃",
                            Status = 1
                        });
                });

            modelBuilder.Entity("HRIS.Domain.Models.Entities.EmployeeVersion", b =>
                {
                    b.Property<DateTime>("Version")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Version");

                    b.ToTable("EmployeeVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
