// <auto-generated />
using System;
using HRIS.Infrastructure.DataAccess.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRIS.Infrastructure.Migrations
{
    [DbContext(typeof(HRISDbContext))]
    [Migration("20231112040149_AddHRISTables")]
    partial class AddHRISTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRIS.Domain.Models.Entities.Config", b =>
                {
                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Section", "Key");

                    b.ToTable("Configs");

                    b.HasData(
                        new
                        {
                            Section = "SYSTEM",
                            Key = "ID_NUMBER_FORMAT",
                            Value = "{0}-{1}-{2}"
                        },
                        new
                        {
                            Section = "SYSTEM",
                            Key = "ID_NUMBER_DIGIT",
                            Value = "7"
                        },
                        new
                        {
                            Section = "SYSTEM",
                            Key = "ID_NUMBER_EMPPLOYEE_PREFIX",
                            Value = "EMP"
                        });
                });

            modelBuilder.Entity("HRIS.Domain.Models.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79695bdb-6f06-4c48-83ee-931136dd6791"),
                            BirthDate = new DateTime(2023, 11, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 11, 21, 32, 13, 728, DateTimeKind.Local).AddTicks(6991),
                            CreatedBy = "Molly_Bernhard76@hotmail.com",
                            FirstName = "Myrtis",
                            Gender = "Male",
                            LastName = "Schaden",
                            MiddleName = "穘ຘᭌ끼䩈陝䵈鑢蕕",
                            Number = "᫃ṁꛛ饢讱缹궐牎籁강",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("857526dd-4588-a1af-fde4-4f3d8748f37d"),
                            BirthDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 30, 20, 59, 58, 106, DateTimeKind.Local).AddTicks(5365),
                            CreatedBy = "Vern.Schaden20@gmail.com",
                            FirstName = "Mireille",
                            Gender = "Male",
                            LastName = "Kunde",
                            MiddleName = "�솺汱餎蠲ꀱ뷈㷷᪢꣗",
                            Number = "㍑厯仪䇞争魫涝",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1acaab7d-5a6d-32bd-daba-fbd997c2c00c"),
                            BirthDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 25, 5, 33, 48, 386, DateTimeKind.Local).AddTicks(9759),
                            CreatedBy = "Dayana22@yahoo.com",
                            FirstName = "Catharine",
                            Gender = "Female",
                            LastName = "Orn",
                            MiddleName = "䉨࿄ᣉ鸵䳁湳賾ᛅ",
                            Number = "䀌㒿⿫滲㪍湦⎵㈣",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("68f44133-4465-04c9-d45e-b8f33d26c2bf"),
                            BirthDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 10, 14, 4, 19, 880, DateTimeKind.Local).AddTicks(7460),
                            CreatedBy = "Jaquan_Haley@gmail.com",
                            FirstName = "Carmela",
                            Gender = "Male",
                            LastName = "Dickens",
                            MiddleName = "ꍷ骭횀⻦魎ḻḰꔛ㏇偓",
                            Number = "㲵㞷圻氎쉛懤㨧⠩",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("098a3538-98ae-4bb3-1420-b861708f1b90"),
                            BirthDate = new DateTime(2023, 6, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 10, 0, 31, 25, 578, DateTimeKind.Local).AddTicks(7328),
                            CreatedBy = "Carley59@gmail.com",
                            FirstName = "Stefan",
                            Gender = "Male",
                            LastName = "Cassin",
                            MiddleName = "ퟌ᧝䁲涤忡酙⯷ꌲ귗",
                            Number = "窙꙾을�㷷펟繞뢥ള슚",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c21300bf-6a8d-227a-5223-94dcc2b17c9c"),
                            BirthDate = new DateTime(2023, 9, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 15, 6, 40, 50, 965, DateTimeKind.Local).AddTicks(4811),
                            CreatedBy = "Rico.Ledner39@gmail.com",
                            FirstName = "Tristian",
                            Gender = "Female",
                            LastName = "Greenfelder",
                            MiddleName = "殥精㞢ꈩ覒�뉈ṁ灔緽",
                            Number = "茿鲎Ү黋撊驢袼",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4391637e-3623-3977-5c69-8adb1f9d8cda"),
                            BirthDate = new DateTime(2023, 1, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 18, 19, 29, 13, 440, DateTimeKind.Local).AddTicks(2502),
                            CreatedBy = "Eleazar.Schuppe6@yahoo.com",
                            FirstName = "Rebecca",
                            Gender = "Male",
                            LastName = "Corkery",
                            MiddleName = "靡쟖쾑坏�稉瑈",
                            Number = "쀅腱ꌇ괮並寈M㋹Ọ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9d008b76-c445-436e-f32b-30354430bf96"),
                            BirthDate = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 15, 19, 25, 36, 901, DateTimeKind.Local).AddTicks(7252),
                            CreatedBy = "Brent54@hotmail.com",
                            FirstName = "Isac",
                            Gender = "Female",
                            LastName = "Crist",
                            MiddleName = "曭殇웵뿑膵ڐ聚挒쵬",
                            Number = "⾊݁膜鎮Ⰶ놫䘦�묓",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("67f284f2-86ff-7b7b-2940-b8ca1f4f1f7d"),
                            BirthDate = new DateTime(2023, 7, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 17, 15, 37, 9, 633, DateTimeKind.Local).AddTicks(7673),
                            CreatedBy = "Shanel.Bradtke@hotmail.com",
                            FirstName = "Maximillian",
                            Gender = "Female",
                            LastName = "Reynolds",
                            MiddleName = "�繵⊗儘뀸┦랎䷎ඩߗ",
                            Number = "ꢳ鵗걅㕌㾖᭛⇚뇽",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("a3ed64b3-ad22-c8cf-21ad-f7142b2908fd"),
                            BirthDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 30, 7, 31, 33, 28, DateTimeKind.Local).AddTicks(1207),
                            CreatedBy = "Dion_Heaney@hotmail.com",
                            FirstName = "Maegan",
                            Gender = "Male",
                            LastName = "Jones",
                            MiddleName = "ኒ੏劐ꨖ歳ඛ䋏�鵶",
                            Number = "㶝ᳵ덴豚Ƌ즭鍭烵耺",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("32d378b3-349d-5201-5458-6d2833e76740"),
                            BirthDate = new DateTime(2023, 1, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 21, 5, 32, 37, 121, DateTimeKind.Local).AddTicks(7831),
                            CreatedBy = "Cullen_Roberts99@hotmail.com",
                            FirstName = "Geovany",
                            Gender = "Male",
                            LastName = "Satterfield",
                            MiddleName = "驮㷎닖墔嵅阔Ὼ伨",
                            Number = "륥ꩮ蠶괵ꫣﵨ妰࿮捘ᇌ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cd9ad59a-12fa-302d-e4b8-218a7bd28555"),
                            BirthDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 21, 22, 55, 22, 440, DateTimeKind.Local).AddTicks(2794),
                            CreatedBy = "Neha52@gmail.com",
                            FirstName = "Winston",
                            Gender = "Female",
                            LastName = "Witting",
                            MiddleName = "Ⓓ擌卸飦䇰Ḍ⚘༳먠",
                            Number = "�巿켮�㵯ҵ矉룡㒜詣",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("08dc4d4a-f5fb-bdb3-0e18-f4737679429e"),
                            BirthDate = new DateTime(2023, 5, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 24, 22, 17, 55, 252, DateTimeKind.Local).AddTicks(956),
                            CreatedBy = "Kory_Satterfield40@gmail.com",
                            FirstName = "Ezekiel",
                            Gender = "Male",
                            LastName = "Schuppe",
                            MiddleName = "䇔脈⪼᫼Ṡ䲎�扅⡮⯘",
                            Number = "큔ᣃ跛뼿吢疧쁌杷ￚ힨",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f91032c3-880b-8b7f-c5fa-71523b00ad53"),
                            BirthDate = new DateTime(2023, 10, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 29, 12, 27, 43, 749, DateTimeKind.Local).AddTicks(24),
                            CreatedBy = "Everardo_Wuckert87@gmail.com",
                            FirstName = "Carrie",
                            Gender = "Female",
                            LastName = "Donnelly",
                            MiddleName = "랲嘯វ绀須쿭䙊쌕ࣤ랝",
                            Number = "儴糖奭⊝␉髿텗ӗ簘",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3aa543dc-c1f4-c75d-a198-2fff331211fd"),
                            BirthDate = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 3, 18, 10, 24, 323, DateTimeKind.Local).AddTicks(6763),
                            CreatedBy = "Octavia37@yahoo.com",
                            FirstName = "Bobbie",
                            Gender = "Female",
                            LastName = "Olson",
                            MiddleName = "܃爬듶髖㗱骆陋帿덴",
                            Number = "楸⤈罟謂໳鮾",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("772f6822-02b2-dfa1-2a16-10e612daf8af"),
                            BirthDate = new DateTime(2023, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 15, 5, 45, 19, 217, DateTimeKind.Local).AddTicks(6536),
                            CreatedBy = "Tristian16@gmail.com",
                            FirstName = "Annette",
                            Gender = "Male",
                            LastName = "Gottlieb",
                            MiddleName = "⠭奟寀Ṇ케拿Ց",
                            Number = "ꮎꄂ髀�䝙ꜰ턽䯭",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8cbe6815-9a33-61ab-2ed7-b69028b4b4bb"),
                            BirthDate = new DateTime(2023, 9, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 29, 4, 52, 17, 634, DateTimeKind.Local).AddTicks(6266),
                            CreatedBy = "Kenyatta_Russel3@yahoo.com",
                            FirstName = "Gerardo",
                            Gender = "Female",
                            LastName = "Wolff",
                            MiddleName = "놂甪帑辪蚖녶訮拾诨",
                            Number = "ꄶ➮�뎥㖸ၙ퀹꘹㗹᳎",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8d0d4731-ff82-b06b-3ea3-b2d9dd549261"),
                            BirthDate = new DateTime(2023, 8, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 30, 1, 29, 11, 546, DateTimeKind.Local).AddTicks(4008),
                            CreatedBy = "Izabella_Kreiger@yahoo.com",
                            FirstName = "Ferne",
                            Gender = "Male",
                            LastName = "Schuster",
                            MiddleName = "給葞퐻濍ꮤ䥑ꗫ뀔",
                            Number = "鄖錎兩ೃ癘喵Გ󯜨",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("778988d1-b379-bc36-1ccc-a5058ea79dfb"),
                            BirthDate = new DateTime(2023, 1, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 16, 19, 9, 37, 622, DateTimeKind.Local).AddTicks(8989),
                            CreatedBy = "Talia_Zieme10@gmail.com",
                            FirstName = "Hailey",
                            Gender = "Male",
                            LastName = "Harris",
                            MiddleName = "豑㜰癐ᔁ场⁄桙勹㓁",
                            Number = "ࣄȸ탨㿞�쥐",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d2204535-aeae-d700-dc56-deb92dbe2da3"),
                            BirthDate = new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 28, 19, 25, 14, 626, DateTimeKind.Local).AddTicks(108),
                            CreatedBy = "Eulalia_Keebler@gmail.com",
                            FirstName = "Winona",
                            Gender = "Female",
                            LastName = "Jaskolski",
                            MiddleName = "徉갴䴁鼁嘒㊐䕥闑攣矟",
                            Number = "汞ㅇ�쿤臜왧鈏쬽",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("417c1395-2d12-5a4b-41c5-b1e0303da97b"),
                            BirthDate = new DateTime(2023, 2, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 5, 23, 16, 56, 167, DateTimeKind.Local).AddTicks(744),
                            CreatedBy = "Dahlia_Toy41@yahoo.com",
                            FirstName = "Lourdes",
                            Gender = "Male",
                            LastName = "Brekke",
                            MiddleName = "燬ꦏ簉�沋껩荑⪘�㉟",
                            Number = "희痯仇홹놂띩獚ే䡘뭖",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("96309556-d41b-7579-0ad5-3f78e21be0e6"),
                            BirthDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 11, 17, 53, 16, 146, DateTimeKind.Local).AddTicks(7635),
                            CreatedBy = "Johnathan_Littel@yahoo.com",
                            FirstName = "Mervin",
                            Gender = "Female",
                            LastName = "Stroman",
                            MiddleName = "萖戮殢푯獚飙㈪퍸䗻熮",
                            Number = "沎㷚动㔼糛饣﷯녻",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4329aadf-efc2-3e93-db09-6b06fbf2d33e"),
                            BirthDate = new DateTime(2023, 1, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 30, 11, 51, 20, 910, DateTimeKind.Local).AddTicks(9807),
                            CreatedBy = "Kaley_Jerde@yahoo.com",
                            FirstName = "Rolando",
                            Gender = "Male",
                            LastName = "Harris",
                            MiddleName = "ׄ㥄ᙗꑏ⺕壋摓Ƙꪥ秽",
                            Number = "㷺蕭鈜ᜈಱ똤妘叻䇝",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("e4edffc1-0d8d-3bf6-6d4b-880f4c4753de"),
                            BirthDate = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 14, 10, 21, 47, 54, DateTimeKind.Local).AddTicks(4424),
                            CreatedBy = "Conor61@hotmail.com",
                            FirstName = "Andres",
                            Gender = "Male",
                            LastName = "Wilderman",
                            MiddleName = "峆㺵㫝콗᾽宴㒑�",
                            Number = "媛②屐姃堟ﭩ是匞שּׂ",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a26f7677-f234-4685-f7db-9324220da139"),
                            BirthDate = new DateTime(2023, 10, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 4, 21, 37, 49, 221, DateTimeKind.Local).AddTicks(1588),
                            CreatedBy = "Leann.Connelly84@hotmail.com",
                            FirstName = "Hassie",
                            Gender = "Female",
                            LastName = "Morar",
                            MiddleName = "˵ở緥꥙࠳扨ޥﵣ",
                            Number = "숕ቈ䋰�䏣極�䄳ᤗ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("6ff85d89-b671-b79f-533a-1b4e144c2534"),
                            BirthDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 14, 9, 13, 49, 140, DateTimeKind.Local).AddTicks(777),
                            CreatedBy = "Reina91@hotmail.com",
                            FirstName = "Cesar",
                            Gender = "Male",
                            LastName = "Wiza",
                            MiddleName = "㖰ꊥ鮐ﮈ䐮䵛⚍襐ᓉꑤ",
                            Number = "郤�躁鲚깘蕬䫷⺳ૂ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("eb3b7b83-2bf6-19de-030a-cd85d68330f6"),
                            BirthDate = new DateTime(2023, 6, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 30, 10, 10, 59, 970, DateTimeKind.Local).AddTicks(2871),
                            CreatedBy = "Lois.Glover@gmail.com",
                            FirstName = "Abdul",
                            Gender = "Male",
                            LastName = "Sanford",
                            MiddleName = "惝앾꺄恪젎ആ阥拆",
                            Number = "䂍螤��㩘欋ⰳꦈ쀴",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("62554f22-2982-6396-324b-22b6d80a3801"),
                            BirthDate = new DateTime(2023, 3, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 14, 16, 32, 44, 135, DateTimeKind.Local).AddTicks(5510),
                            CreatedBy = "Eduardo_Effertz29@yahoo.com",
                            FirstName = "Pauline",
                            Gender = "Female",
                            LastName = "Hermann",
                            MiddleName = "充⋔コ�倈唦ઠ",
                            Number = "ᮨࢲ侭덝뀨᷄ꕲ꽈",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("81d9ec1c-23d4-f161-0195-b69d4ac0c9c5"),
                            BirthDate = new DateTime(2023, 10, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 13, 8, 50, 48, 127, DateTimeKind.Local).AddTicks(2243),
                            CreatedBy = "Joshuah15@gmail.com",
                            FirstName = "Grady",
                            Gender = "Female",
                            LastName = "D'Amore",
                            MiddleName = "徝ⰴ㭰ͪ㙔ꆡ퍜⎬迗",
                            Number = "�点㨎폽뉅隀ꏋ樰뢰",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("4c65a9c0-4e25-7999-3ffa-fc0d90156bca"),
                            BirthDate = new DateTime(2023, 7, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 17, 1, 59, 16, 189, DateTimeKind.Local).AddTicks(2439),
                            CreatedBy = "Sonny.Gutmann52@hotmail.com",
                            FirstName = "Maryse",
                            Gender = "Female",
                            LastName = "Torphy",
                            MiddleName = "ꄲ剠켅鳄쒞参뫊馻팙唵",
                            Number = "᫊ꧣ쌸飃譖溢虍茡갻",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("7e940b6e-9c6f-a4c7-7510-9a8e34d7aa11"),
                            BirthDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 27, 1, 9, 29, 499, DateTimeKind.Local).AddTicks(439),
                            CreatedBy = "Ressie.Emard@yahoo.com",
                            FirstName = "Garrison",
                            Gender = "Male",
                            LastName = "Leuschke",
                            MiddleName = "啙榆Ѳꕩ댘媌䟾〲뒃鹉",
                            Number = "ᡲ⭰ᓁ�٧ﲾ䟙惕ໍ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("afdd754c-75f3-485d-3b14-29572626c66e"),
                            BirthDate = new DateTime(2023, 7, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 13, 9, 54, 47, 230, DateTimeKind.Local).AddTicks(1017),
                            CreatedBy = "Geraldine_Williamson@hotmail.com",
                            FirstName = "Darien",
                            Gender = "Male",
                            LastName = "Quitzon",
                            MiddleName = "꣉筘颖庑갟毎Ⱕ預䏘劏",
                            Number = "ስ⍴匹೦奍ꧨ嶸գꛬ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8b9902c9-070d-8399-55cc-05ef94e84f64"),
                            BirthDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 10, 19, 33, 39, 152, DateTimeKind.Local).AddTicks(7372),
                            CreatedBy = "Uriah.Bogan91@gmail.com",
                            FirstName = "Rachel",
                            Gender = "Female",
                            LastName = "Kertzmann",
                            MiddleName = "䖰蕥맫Ā艇䏞殏㳒낹",
                            Number = "뿞ह⣴繉鯞於ⵙ㒼敆᭢",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ceec5e4d-9d06-8a60-5606-7e987ef7f5ee"),
                            BirthDate = new DateTime(2023, 7, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 29, 7, 57, 3, 798, DateTimeKind.Local).AddTicks(371),
                            CreatedBy = "Amir.Kilback1@yahoo.com",
                            FirstName = "Vida",
                            Gender = "Male",
                            LastName = "Yost",
                            MiddleName = "睝驪瀋辅⥂둓�ᥜ祀",
                            Number = "ꉸ䝧㻜駈徕珆轚ⵥﮘ",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("7cd1776f-8378-420c-947f-922799972364"),
                            BirthDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 9, 0, 29, 27, 633, DateTimeKind.Local).AddTicks(5123),
                            CreatedBy = "Jedidiah81@hotmail.com",
                            FirstName = "Salma",
                            Gender = "Male",
                            LastName = "Bahringer",
                            MiddleName = "懞큲登ᚫ⥘⌴쀡ߎ䪎븋",
                            Number = "쵅郤楥ᅑ�綩㫽焒",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5472e8d7-9058-195b-a48f-9b81b398c227"),
                            BirthDate = new DateTime(2023, 9, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 3, 22, 43, 30, 298, DateTimeKind.Local).AddTicks(5907),
                            CreatedBy = "Petra.Ortiz49@yahoo.com",
                            FirstName = "Zaria",
                            Gender = "Male",
                            LastName = "Lueilwitz",
                            MiddleName = "䩓庛ឨራ⹝Ҩ箈⃩餃罹",
                            Number = "馍❼�뗳彍鑊ꈞ牬謢㎻",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d18e82da-3411-6bd2-5c5f-d7d4dc6cc9db"),
                            BirthDate = new DateTime(2023, 5, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 2, 8, 44, 18, 49, DateTimeKind.Local).AddTicks(3963),
                            CreatedBy = "Katlynn_Terry63@yahoo.com",
                            FirstName = "Trinity",
                            Gender = "Male",
                            LastName = "Schumm",
                            MiddleName = "੻﬍ᛲ睋퐶埒餺ﾧ┪귺",
                            Number = "푦폪ꯪ⏧浘꩹ꇧ阌嫲",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("bff249a1-b165-c87b-0f91-96db5cdcf422"),
                            BirthDate = new DateTime(2023, 2, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 2, 23, 30, 58, 740, DateTimeKind.Local).AddTicks(7229),
                            CreatedBy = "Yasmeen.Kshlerin42@gmail.com",
                            FirstName = "Chris",
                            Gender = "Male",
                            LastName = "Gutmann",
                            MiddleName = "﻿꫅鈶嵂ᵓ招롓",
                            Number = "�窣㏵隥ኵ魚ⱆ⬴팙峸",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("8926abb5-f0ed-edee-2ea7-7d426184e751"),
                            BirthDate = new DateTime(2023, 10, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 26, 18, 16, 11, 3, DateTimeKind.Local).AddTicks(4563),
                            CreatedBy = "Hilario_Gutmann95@hotmail.com",
                            FirstName = "Kitty",
                            Gender = "Female",
                            LastName = "Welch",
                            MiddleName = "栞纝�☵ꊣ街�鮬",
                            Number = "묦䕖�䥵説숶ꝏ쵌朁푱",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("25104cd1-7a67-9185-5cf0-30b2b50efa28"),
                            BirthDate = new DateTime(2023, 7, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 21, 5, 34, 26, 996, DateTimeKind.Local).AddTicks(4934),
                            CreatedBy = "Eleanora_Deckow@hotmail.com",
                            FirstName = "Caden",
                            Gender = "Male",
                            LastName = "Torphy",
                            MiddleName = "繿竄컬炆⎅裡�䖊",
                            Number = "䚮Ϡ黴啢Ồ膹굛鿢㹐",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("86999680-c54a-4b22-2363-d64a9efe5432"),
                            BirthDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 10, 10, 48, 15, 401, DateTimeKind.Local).AddTicks(1101),
                            CreatedBy = "Alec.Borer@gmail.com",
                            FirstName = "Regan",
                            Gender = "Female",
                            LastName = "Spencer",
                            MiddleName = "ꋾದ搇䢠娦껝ࣨ噃",
                            Number = "籦㻇⌕�좁䖡碀꽁䀱",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8ceac72e-8357-ee8c-e2e6-25f897626b33"),
                            BirthDate = new DateTime(2023, 6, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 10, 10, 4, 14, 456, DateTimeKind.Local).AddTicks(9605),
                            CreatedBy = "Harvey_Gerlach85@yahoo.com",
                            FirstName = "Enrique",
                            Gender = "Male",
                            LastName = "Schaden",
                            MiddleName = "ʆ雿ﹻ⥨쫽儷옂㍜",
                            Number = "ꬕ畩鎭᭺㘙瓤怢꩑ቤ꠆",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("87a8d2ec-a1b0-509e-5a2d-4ac1e88ef32b"),
                            BirthDate = new DateTime(2023, 10, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 28, 7, 42, 48, 872, DateTimeKind.Local).AddTicks(4383),
                            CreatedBy = "Cleve.Doyle@gmail.com",
                            FirstName = "Andreane",
                            Gender = "Female",
                            LastName = "Goldner",
                            MiddleName = "욳欌渏쓮䍰孹鸘灅䏨投",
                            Number = "쀬얽仾椏䉗菳弎筲",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("c930a0dd-1ea0-81e8-c31a-332853c628a5"),
                            BirthDate = new DateTime(2023, 3, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 31, 21, 41, 51, 422, DateTimeKind.Local).AddTicks(6109),
                            CreatedBy = "Magdalena6@gmail.com",
                            FirstName = "Edgar",
                            Gender = "Male",
                            LastName = "Schneider",
                            MiddleName = "ᨃ쪤࠱ㄫ엂屒⿟씐퀒",
                            Number = "㉚堌䶵逞悴팭靗䏪ጦ偟",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8d8fd338-88b8-baa2-7bea-aa57349a8e14"),
                            BirthDate = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 6, 11, 45, 42, 426, DateTimeKind.Local).AddTicks(2134),
                            CreatedBy = "Xander37@yahoo.com",
                            FirstName = "Triston",
                            Gender = "Male",
                            LastName = "Kassulke",
                            MiddleName = "謲Ủ�ᒾ鍩ꮭ꘮䞡",
                            Number = "靬ގ荮䅟⍚﯆≼촁棔",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("109e1046-98e6-be4d-3b3f-77e604c09e55"),
                            BirthDate = new DateTime(2023, 3, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 30, 15, 46, 28, 693, DateTimeKind.Local).AddTicks(9736),
                            CreatedBy = "Carolyne_Hansen@gmail.com",
                            FirstName = "Kayley",
                            Gender = "Male",
                            LastName = "Bogisich",
                            MiddleName = "雱Ꝺὺﲡ킆⫉ꖏཱི䰎亀",
                            Number = "礠囕훵Ր舨钾麟僈牽",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("739d9238-d188-0690-acc4-4b4835f33d9c"),
                            BirthDate = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 10, 16, 10, 51, 480, DateTimeKind.Local).AddTicks(5038),
                            CreatedBy = "Layla_Weber74@yahoo.com",
                            FirstName = "Eva",
                            Gender = "Female",
                            LastName = "Steuber",
                            MiddleName = "Ꮯﶢ㼴蠴辜ﳶ墸淘㑭",
                            Number = "븗�鰘⦯㨚蚆⺯뮪䷐",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8cfebe70-55af-5b1b-cd74-8a758affdcc6"),
                            BirthDate = new DateTime(2023, 2, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 3, 6, 29, 47, 178, DateTimeKind.Local).AddTicks(6208),
                            CreatedBy = "Vivienne46@hotmail.com",
                            FirstName = "Flo",
                            Gender = "Female",
                            LastName = "Gutkowski",
                            MiddleName = "�ꅱ卻諭黙壐哞厓镰",
                            Number = "嚀ഷ⠏≹睶ӳ窌령",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("83dd1923-79e0-f05b-be81-977851e1d1d8"),
                            BirthDate = new DateTime(2022, 11, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 11, 17, 2, 4, 357, DateTimeKind.Local).AddTicks(8351),
                            CreatedBy = "Lexie.Gutmann54@gmail.com",
                            FirstName = "Kelton",
                            Gender = "Female",
                            LastName = "Connelly",
                            MiddleName = "㟮普絯ゴ龄玁퀋照验",
                            Number = "옆唱蚃ꭑᴈ�芔य़ᙧ㱉",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("ada78a35-2971-ebd9-6ee6-a67aa396494e"),
                            BirthDate = new DateTime(2023, 8, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 15, 1, 42, 30, 460, DateTimeKind.Local).AddTicks(2523),
                            CreatedBy = "Jabari.White2@gmail.com",
                            FirstName = "Abdiel",
                            Gender = "Male",
                            LastName = "Armstrong",
                            MiddleName = "ᬘᛷ಍�䅩ᗑ뉅ꪡ쏖",
                            Number = "ꆔ췦�ପ�କ┑橁",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("348a3466-8070-3d53-3355-e4f4bdc942f2"),
                            BirthDate = new DateTime(2022, 12, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 9, 19, 30, 57, 911, DateTimeKind.Local).AddTicks(1514),
                            CreatedBy = "Antonetta19@yahoo.com",
                            FirstName = "Jesse",
                            Gender = "Male",
                            LastName = "VonRueden",
                            MiddleName = "栲⒃녶뱧擵鞚᫃匐鍽",
                            Number = "ᴻ㨍夃㎴讠策�漂",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("37c0c6a0-2662-63db-2fcd-875251d5567e"),
                            BirthDate = new DateTime(2023, 5, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 17, 10, 33, 30, 930, DateTimeKind.Local).AddTicks(6944),
                            CreatedBy = "Dulce34@yahoo.com",
                            FirstName = "Raphael",
                            Gender = "Female",
                            LastName = "Hilpert",
                            MiddleName = "䱜៾橷裮⡤桃㴜痬斊",
                            Number = "⟊钓輎ふ縖쿎ⷨ૞榜瓢",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("9c2e9dc9-6171-4718-a53e-6505c238831d"),
                            BirthDate = new DateTime(2023, 7, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 22, 20, 46, 46, 437, DateTimeKind.Local).AddTicks(5487),
                            CreatedBy = "Queen_Osinski96@gmail.com",
                            FirstName = "Wyatt",
                            Gender = "Female",
                            LastName = "Jast",
                            MiddleName = "抮臈닽뮚럎癵쀩\r产",
                            Number = "꽘趔饛䍐ᣥڦ㊑蒈唉",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("83666d3c-3f21-7ec6-4679-c5f0035e3ac2"),
                            BirthDate = new DateTime(2023, 10, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 16, 13, 47, 45, 535, DateTimeKind.Local).AddTicks(5050),
                            CreatedBy = "Hassie_Orn85@hotmail.com",
                            FirstName = "Harley",
                            Gender = "Female",
                            LastName = "Rath",
                            MiddleName = "�ㄩ剑;䑑贜떙䄲�",
                            Number = "蘿ꣿ濟藥걌倉㝯＠/",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("60fe2526-5c78-2644-c06c-9d3e1f5efea4"),
                            BirthDate = new DateTime(2023, 10, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 26, 23, 41, 8, 123, DateTimeKind.Local).AddTicks(5192),
                            CreatedBy = "Kali5@yahoo.com",
                            FirstName = "Colleen",
                            Gender = "Male",
                            LastName = "D'Amore",
                            MiddleName = "ꊗꗬ廫檽⪼뱔ᣄ",
                            Number = "깅ࣀ냸㪁㺍뚓錶붍慃চ",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6314e3f5-4868-84b1-54a8-00ac3100a22c"),
                            BirthDate = new DateTime(2022, 12, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 1, 8, 6, 41, 114, DateTimeKind.Local).AddTicks(7578),
                            CreatedBy = "Bud6@hotmail.com",
                            FirstName = "Kattie",
                            Gender = "Male",
                            LastName = "Schneider",
                            MiddleName = "뫭䢈舥⁇﹢뽕쿨迄콵",
                            Number = "惦ﵦ흦ꄫⱇ梭嬊�Ꭺ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("f62a3b4d-faf0-645a-6860-6207fb17f69c"),
                            BirthDate = new DateTime(2022, 12, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 5, 1, 53, 25, 747, DateTimeKind.Local).AddTicks(5984),
                            CreatedBy = "Lamar.Sauer65@yahoo.com",
                            FirstName = "Terry",
                            Gender = "Female",
                            LastName = "Glover",
                            MiddleName = "뉌膴兼鴣來觻ﶚⲡ✤",
                            Number = "迹꩜ᶷ댐凞螩㕌鵎蠟",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2b3e7ada-0777-47ba-ade0-55b5bd43282a"),
                            BirthDate = new DateTime(2023, 1, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 26, 9, 47, 26, 5, DateTimeKind.Local).AddTicks(2652),
                            CreatedBy = "Maeve90@yahoo.com",
                            FirstName = "Layla",
                            Gender = "Female",
                            LastName = "Volkman",
                            MiddleName = "즩얢蹼꩏෿鳘㩠舷簷夋",
                            Number = "ꀳ�屢ฏм㲝萧靹챏",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4529e205-a653-50bc-f65d-e24609cee40b"),
                            BirthDate = new DateTime(2023, 6, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 11, 14, 57, 40, 182, DateTimeKind.Local).AddTicks(9277),
                            CreatedBy = "Rosalind_Hegmann@hotmail.com",
                            FirstName = "Jaylin",
                            Gender = "Female",
                            LastName = "Flatley",
                            MiddleName = "䶠喞怰㿄새翉⨵葴",
                            Number = "ᄬ狦司펄갿쌢䫠㤚䳗",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("36c80997-fca7-1bef-c990-028c4d6061b2"),
                            BirthDate = new DateTime(2023, 2, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 6, 10, 7, 26, 59, 294, DateTimeKind.Local).AddTicks(2624),
                            CreatedBy = "Madisyn.Strosin69@hotmail.com",
                            FirstName = "Armando",
                            Gender = "Male",
                            LastName = "Feeney",
                            MiddleName = "犊Ꟈ㈁ꖾ䂯�䧘꫄顶ꪱ",
                            Number = "馥趧싨쓞ꊉ片賃꺪뷯籰",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b2ba7bf8-95b1-e4de-f0aa-15afb97d3b93"),
                            BirthDate = new DateTime(2023, 10, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 9, 1, 11, 28, 444, DateTimeKind.Local).AddTicks(3230),
                            CreatedBy = "Erna.Hodkiewicz69@gmail.com",
                            FirstName = "Cynthia",
                            Gender = "Male",
                            LastName = "Harris",
                            MiddleName = "茛㵩嗝칎Ἠ倣Ꮱ珷෾Ĵ",
                            Number = "ؘ໪谑蹙읢㘁轟欔싀",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3ee027a0-13c1-7851-7577-ace534788f90"),
                            BirthDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 5, 8, 37, 12, 81, DateTimeKind.Local).AddTicks(4770),
                            CreatedBy = "Ezra.Marquardt73@hotmail.com",
                            FirstName = "Eloy",
                            Gender = "Male",
                            LastName = "Mueller",
                            MiddleName = "⩸굫迋ࡾ⒁꓌఼",
                            Number = "胇啾�掋٣睾䛚묜↙뢔",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("245622cd-9173-3216-d501-bf75106365db"),
                            BirthDate = new DateTime(2023, 3, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 5, 4, 1, 2, 691, DateTimeKind.Local).AddTicks(5852),
                            CreatedBy = "Samanta38@gmail.com",
                            FirstName = "Lenora",
                            Gender = "Female",
                            LastName = "Turcotte",
                            MiddleName = "⎶奆���雃丢닎",
                            Number = "ୱ鹖堆붊릥얞㛸羖",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3c8250af-6a60-609c-5d9a-23f83eac9791"),
                            BirthDate = new DateTime(2023, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 29, 16, 41, 35, 577, DateTimeKind.Local).AddTicks(4095),
                            CreatedBy = "Sally_Nader66@yahoo.com",
                            FirstName = "Mya",
                            Gender = "Male",
                            LastName = "Steuber",
                            MiddleName = "㮨�㚝腪叱�銅碵榐혦",
                            Number = "䷔´傓鴻৪蹖宍谧ᨀ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a017fe36-7db2-9c3b-8f04-6184c1493326"),
                            BirthDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 21, 3, 26, 9, 120, DateTimeKind.Local).AddTicks(9348),
                            CreatedBy = "Randall.Hansen55@yahoo.com",
                            FirstName = "Florida",
                            Gender = "Male",
                            LastName = "Konopelski",
                            MiddleName = "殊匕낼漋쵹쀺᪷멾㦉燭",
                            Number = "䞉饻憖ᶓ컦틛儮쐸繳",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d7f9c19f-c5dd-bb88-dd46-c6131e38fb8f"),
                            BirthDate = new DateTime(2023, 1, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 18, 0, 51, 22, 861, DateTimeKind.Local).AddTicks(8446),
                            CreatedBy = "Minerva86@gmail.com",
                            FirstName = "Edd",
                            Gender = "Female",
                            LastName = "Kovacek",
                            MiddleName = "ퟱ귚ᖈᚁ᳛Ⱃ",
                            Number = "榱褆돿♃鴢窢ᗖ쟄翫",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("de6f110c-a5d2-58b9-9555-b2d0692bb530"),
                            BirthDate = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 29, 18, 29, 21, 133, DateTimeKind.Local).AddTicks(5685),
                            CreatedBy = "Jonathan32@gmail.com",
                            FirstName = "Clifford",
                            Gender = "Female",
                            LastName = "Erdman",
                            MiddleName = "翇鲯映ᘾ勽䀭쐋",
                            Number = "쬼ព傝뤰텿蒽湥탐",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("b151d8a0-bb5e-7061-38b5-349d47cc1070"),
                            BirthDate = new DateTime(2022, 11, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 27, 7, 29, 6, 8, DateTimeKind.Local).AddTicks(3671),
                            CreatedBy = "Anastacio24@yahoo.com",
                            FirstName = "Beryl",
                            Gender = "Male",
                            LastName = "Breitenberg",
                            MiddleName = "袱扢蔎苋炍᫂以끗",
                            Number = "顁祡ᛌ؜ℎ䍙䢆뵡톲",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d2544d81-2a04-a64d-5be4-7feef6e87be0"),
                            BirthDate = new DateTime(2023, 4, 3, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 11, 21, 50, 6, 438, DateTimeKind.Local).AddTicks(5864),
                            CreatedBy = "Angie.Denesik30@hotmail.com",
                            FirstName = "Hardy",
                            Gender = "Female",
                            LastName = "Beier",
                            MiddleName = "鯵漍隥絖運䧂铆☣刚ퟳ",
                            Number = "㱊ǿꙟ췟ꍤ蟌폇嗘",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("3dea3226-8882-3e34-fd1a-41d508cba01a"),
                            BirthDate = new DateTime(2023, 7, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 31, 19, 32, 5, 830, DateTimeKind.Local).AddTicks(8050),
                            CreatedBy = "Blake.Kreiger@yahoo.com",
                            FirstName = "Nyah",
                            Gender = "Male",
                            LastName = "Kertzmann",
                            MiddleName = "纘ර␮搹ⴰ뮼좂",
                            Number = "믘☶袪敂勀놉⁞飄�",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("39e22e15-0a7e-3649-9ff4-356a5792db30"),
                            BirthDate = new DateTime(2023, 3, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 6, 5, 15, 59, 889, DateTimeKind.Local).AddTicks(5187),
                            CreatedBy = "Florence_Ortiz@hotmail.com",
                            FirstName = "Lucas",
                            Gender = "Male",
                            LastName = "Lueilwitz",
                            MiddleName = "㨳燨볙︨ፓ�졑闽冇",
                            Number = "砇폲쀋뭔錵蒂簫䬴",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("1bf0ab5d-4d71-45fc-f488-4889250c6b93"),
                            BirthDate = new DateTime(2023, 9, 6, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 11, 4, 9, 15, 37, 694, DateTimeKind.Local).AddTicks(4785),
                            CreatedBy = "Tyree.Lind54@hotmail.com",
                            FirstName = "Jessie",
                            Gender = "Female",
                            LastName = "Schaefer",
                            MiddleName = "ᛖ鄳雐◂╭姌킠唻",
                            Number = "Ƿ뷎᷆鴌餯堹ꉢ枡",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3f8a47a4-96a5-5863-ee43-2d83bdd2ad8b"),
                            BirthDate = new DateTime(2023, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 1, 22, 11, 9, 932, DateTimeKind.Local).AddTicks(2136),
                            CreatedBy = "Yasmin_Ryan7@gmail.com",
                            FirstName = "Ted",
                            Gender = "Female",
                            LastName = "Thiel",
                            MiddleName = "霜翡囃摋袁ᗧ�铦",
                            Number = "፦揧䫉ᬈ瓌韅ﶵ꿕蓏ꯃ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("85244d0d-ad57-f5d2-56e4-4ab5b31b2116"),
                            BirthDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 4, 0, 43, 50, 40, DateTimeKind.Local).AddTicks(3641),
                            CreatedBy = "Aric.Feeney@yahoo.com",
                            FirstName = "Kareem",
                            Gender = "Male",
                            LastName = "Auer",
                            MiddleName = "騞硉Ծ霌솖㗷䈇於覓",
                            Number = "♘泓ﰗ簰軀ᆰ⬿퇾",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("878fd3f1-de07-169e-c2a8-f5f37f8f224d"),
                            BirthDate = new DateTime(2023, 10, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 16, 22, 47, 55, 549, DateTimeKind.Local).AddTicks(8811),
                            CreatedBy = "Cyril89@hotmail.com",
                            FirstName = "Elwin",
                            Gender = "Female",
                            LastName = "Stiedemann",
                            MiddleName = "㵐魰춙뚏䢃䁒闷ʎ좉孄",
                            Number = "먉偓夺꘍佭㱟劫뮧㌗솊",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("fd543d5e-cf06-2c79-67f4-bd35d1de58f3"),
                            BirthDate = new DateTime(2023, 1, 16, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 29, 4, 28, 59, 386, DateTimeKind.Local).AddTicks(2974),
                            CreatedBy = "Eliza_Larson71@hotmail.com",
                            FirstName = "Serena",
                            Gender = "Female",
                            LastName = "Boehm",
                            MiddleName = "῿檻툎節虦⅖⏆뾬搎郯",
                            Number = "臏爜엠뎳伀앝绦ӧ᯵",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("aca658c0-1e0e-068a-b295-85707e599afa"),
                            BirthDate = new DateTime(2023, 3, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 9, 9, 3, 35, 980, DateTimeKind.Local).AddTicks(1032),
                            CreatedBy = "Letitia70@hotmail.com",
                            FirstName = "Cheyanne",
                            Gender = "Female",
                            LastName = "Nikolaus",
                            MiddleName = "뼦弽㛟筥싴㧅ਫ큑䧍",
                            Number = "�事聮ꃅ઴ߎ璠",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("f83ec4c1-7785-b290-b1f9-63fb3eca4953"),
                            BirthDate = new DateTime(2023, 9, 4, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 17, 12, 39, 38, 912, DateTimeKind.Local).AddTicks(9633),
                            CreatedBy = "Marion.Padberg14@yahoo.com",
                            FirstName = "Geovanny",
                            Gender = "Male",
                            LastName = "Lynch",
                            MiddleName = "蔹喼嫱ᢡ짻ཨ蔾",
                            Number = "쓥ᭆ鬦⎜趩䅈嫶o鞢揣",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("4476b8b1-0dec-5aff-03bb-2853ca92172a"),
                            BirthDate = new DateTime(2023, 8, 21, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 25, 1, 0, 15, 128, DateTimeKind.Local).AddTicks(8030),
                            CreatedBy = "Kristian.Bosco@hotmail.com",
                            FirstName = "Vidal",
                            Gender = "Female",
                            LastName = "Jacobs",
                            MiddleName = "袯츳驚䠏隄銚雃刑욆�",
                            Number = "᱃솒狆ꌓꎢ᳥굮葙ꗜ＝",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0eea9664-3840-fdfe-560a-7ac4a3c15cd3"),
                            BirthDate = new DateTime(2023, 9, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 23, 15, 52, 9, 166, DateTimeKind.Local).AddTicks(4953),
                            CreatedBy = "Rosendo_OReilly9@hotmail.com",
                            FirstName = "Roy",
                            Gender = "Female",
                            LastName = "Nikolaus",
                            MiddleName = "癔눏ᜏ쁐ꔛ謟ꡄ탃",
                            Number = "⯙垰睊쵓걆䪥뙃㏬帝�",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("a3c788ae-d8cb-fcb7-14d3-54eb56f38181"),
                            BirthDate = new DateTime(2023, 10, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 5, 4, 15, 50, 8, 886, DateTimeKind.Local).AddTicks(4170),
                            CreatedBy = "Robb_Runolfsson28@gmail.com",
                            FirstName = "Audreanne",
                            Gender = "Male",
                            LastName = "Cassin",
                            MiddleName = "꘦ㇿ飵ꢄ샽囯㦫Ჷ㓥᰺",
                            Number = "に８㔁ݼ賎鄶㸽Ạ",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("09f15164-9060-2895-fd4a-b8189a32e9fc"),
                            BirthDate = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 1, 1, 52, 15, 341, DateTimeKind.Local).AddTicks(4197),
                            CreatedBy = "Marley_Jacobi98@gmail.com",
                            FirstName = "Evans",
                            Gender = "Female",
                            LastName = "Conroy",
                            MiddleName = "侶㇛ξꋡ憤뭪輽뾲ॐ",
                            Number = "綉鹲炅擖쐮鷏ܴԷ�",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("9604dcab-2511-1efd-f0ef-386fc932ef67"),
                            BirthDate = new DateTime(2023, 10, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 28, 21, 44, 39, 650, DateTimeKind.Local).AddTicks(9994),
                            CreatedBy = "Kendall_Wuckert@hotmail.com",
                            FirstName = "Donald",
                            Gender = "Female",
                            LastName = "Luettgen",
                            MiddleName = "殂籮嗘缎댧㸇�焿",
                            Number = "熈㮔ᆟᓙ옅첑ﺨࢮά璒",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("5997e589-67ab-93ce-6e2f-bce5c975ae68"),
                            BirthDate = new DateTime(2023, 6, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 6, 8, 17, 41, 912, DateTimeKind.Local).AddTicks(9580),
                            CreatedBy = "Augusta.Sauer@hotmail.com",
                            FirstName = "Jaren",
                            Gender = "Male",
                            LastName = "Glover",
                            MiddleName = "⌯ჵ镧皠൙ⱛᠭꂕ㤒⎍",
                            Number = "纩袕ᣱ⚙䐚볁ᦳ⮑ጙ",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("da9b23b3-1db4-5c87-c70f-d35f4121d486"),
                            BirthDate = new DateTime(2023, 7, 18, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 11, 27, 0, 32, 56, 37, DateTimeKind.Local).AddTicks(5696),
                            CreatedBy = "Guillermo5@gmail.com",
                            FirstName = "Julius",
                            Gender = "Female",
                            LastName = "Shanahan",
                            MiddleName = "ꗵ辑䬭콂ㄚ？㑿隟檑脛",
                            Number = "际렧觴㗫鋻딳긷颩츴枠",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("824ea798-5aa4-da61-b6fa-38b0e2afc25b"),
                            BirthDate = new DateTime(2023, 5, 2, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 28, 3, 28, 51, 911, DateTimeKind.Local).AddTicks(924),
                            CreatedBy = "Dusty.Walsh@yahoo.com",
                            FirstName = "Lacy",
                            Gender = "Male",
                            LastName = "Zemlak",
                            MiddleName = "�뚗轩俕킟륊詤臯饤ꥮ",
                            Number = "矩赊㡺㈧ㄏჽ禁ꒄ浛幼",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("14cc7dd7-274c-f00d-d218-96bf8d5cc99c"),
                            BirthDate = new DateTime(2023, 8, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 5, 19, 8, 10, 329, DateTimeKind.Local).AddTicks(268),
                            CreatedBy = "Ricardo.Parisian7@gmail.com",
                            FirstName = "Jazmyn",
                            Gender = "Female",
                            LastName = "Stark",
                            MiddleName = "㥄䟦↊朌梺䫨徖䴑",
                            Number = "鈮鄬쫵댞✺噇Ꮮ㒡뛀艰",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("2812a48f-5b00-8bc0-dee5-c95f47f10752"),
                            BirthDate = new DateTime(2023, 8, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 22, 10, 22, 21, 529, DateTimeKind.Local).AddTicks(3034),
                            CreatedBy = "Rhiannon_Weissnat@hotmail.com",
                            FirstName = "Roberta",
                            Gender = "Male",
                            LastName = "McDermott",
                            MiddleName = "啽Ⱔꕟ땗�더㤜֗",
                            Number = "剷ᇿ⥂ﰮ鿾䄟摝潼ᦝ▎",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("cac19750-d2ae-3a12-ce24-829bd6a9509e"),
                            BirthDate = new DateTime(2023, 5, 8, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 12, 7, 56, 1, 520, DateTimeKind.Local).AddTicks(2689),
                            CreatedBy = "Gerard.Buckridge@hotmail.com",
                            FirstName = "Brett",
                            Gender = "Male",
                            LastName = "Lueilwitz",
                            MiddleName = "濵뷟썍౏퓰洁윮◼峬䊜",
                            Number = "㙱謿։ࣧ﶐㒠�ｵ쓙",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("bb5a2681-e158-efd9-3e6a-d7b94fb751cf"),
                            BirthDate = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 1, 5, 17, 34, 39, 853, DateTimeKind.Local).AddTicks(4560),
                            CreatedBy = "Makenzie21@gmail.com",
                            FirstName = "Kristofer",
                            Gender = "Female",
                            LastName = "Rogahn",
                            MiddleName = "㷖舀㊿䧂⍄랎䉲䰋婀兑",
                            Number = "통뀻ឳş덢‿賃ඔ㚎뎡",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("8d387495-fe96-4913-600f-ba0d66c642d5"),
                            BirthDate = new DateTime(2023, 7, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 3, 27, 2, 57, 16, 942, DateTimeKind.Local).AddTicks(7589),
                            CreatedBy = "Allene98@yahoo.com",
                            FirstName = "Cindy",
                            Gender = "Male",
                            LastName = "Flatley",
                            MiddleName = "馆ਅ羮ㇶ�꾼釋ꭍ唑",
                            Number = "엳츎즕砓溸᧒䵤垯",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("5f984d4d-619a-5475-8d51-95e6c28118ae"),
                            BirthDate = new DateTime(2023, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 2, 17, 14, 34, 56, 976, DateTimeKind.Local).AddTicks(4769),
                            CreatedBy = "Rene_Ledner@hotmail.com",
                            FirstName = "Jaron",
                            Gender = "Male",
                            LastName = "Hauck",
                            MiddleName = "�鞧ꍲ㳑쳉�㧛夒",
                            Number = "�䪡ᛚꨳ◣甩Ᏽ䪠",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0e99107d-1e00-14cd-fe3f-dd888b9494dd"),
                            BirthDate = new DateTime(2023, 5, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 12, 22, 8, 59, 427, DateTimeKind.Local).AddTicks(6544),
                            CreatedBy = "Dahlia_Zieme@hotmail.com",
                            FirstName = "Arvid",
                            Gender = "Male",
                            LastName = "Nitzsche",
                            MiddleName = "뜯卍膦ᇞ쯽킝㜌灾뚁播",
                            Number = "ᇳɅ辞员莩ꡞ센碨⮍",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("d42a0150-57f8-e169-26ac-b1900de9bf07"),
                            BirthDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 10, 5, 7, 37, 48, 957, DateTimeKind.Local).AddTicks(2571),
                            CreatedBy = "Malcolm.Hagenes@hotmail.com",
                            FirstName = "Cesar",
                            Gender = "Female",
                            LastName = "Glover",
                            MiddleName = "绂㣌謵ᑣ玐聍킀櫲᝷�",
                            Number = "袞⣿閑姇�⥁诸ᩌ䒫㼕",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("b80e2d17-e336-ca14-85be-8db10581849b"),
                            BirthDate = new DateTime(2023, 8, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 9, 16, 1, 1, 3, 507, DateTimeKind.Local).AddTicks(2470),
                            CreatedBy = "Reyna14@hotmail.com",
                            FirstName = "Gladyce",
                            Gender = "Female",
                            LastName = "Cruickshank",
                            MiddleName = "㵑䣷㤴쟕칼朐켤襤ⲩ闛",
                            Number = "ᢙ阜ၐ䳕瘼ç뿧�൳",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("00530524-f652-a940-67b9-e5771e05e6b3"),
                            BirthDate = new DateTime(2023, 9, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 9, 4, 8, 48, 255, DateTimeKind.Local).AddTicks(5535),
                            CreatedBy = "Theodore.Mills78@yahoo.com",
                            FirstName = "Trenton",
                            Gender = "Female",
                            LastName = "Prosacco",
                            MiddleName = "枨욓ﴭ័잔࿳⮎逦䙫",
                            Number = "㆛땓뻎醋贾﷤䇪",
                            Status = 2
                        },
                        new
                        {
                            Id = new Guid("70b429c4-43f3-a5bd-2762-3c7411169f10"),
                            BirthDate = new DateTime(2023, 8, 11, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2023, 12, 25, 9, 38, 32, 726, DateTimeKind.Local).AddTicks(9338),
                            CreatedBy = "Eriberto23@gmail.com",
                            FirstName = "Alfred",
                            Gender = "Female",
                            LastName = "Cummings",
                            MiddleName = "뫟ﺨᮈ艉㬋仌㸸迌瘋仦",
                            Number = "䰠ᖘ䇑⑟ᦉ腦꭬ት",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("a48c5b46-bf04-1398-72a3-baa23887d7a6"),
                            BirthDate = new DateTime(2023, 4, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 4, 20, 9, 32, 38, 642, DateTimeKind.Local).AddTicks(3306),
                            CreatedBy = "Ally.Okuneva33@hotmail.com",
                            FirstName = "Aurelia",
                            Gender = "Male",
                            LastName = "Schneider",
                            MiddleName = "ꔻ㐛»頺맚걆禸ﾞ몪",
                            Number = "ᜳ㪇鞵僷橹䳒衪잂콎",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("ad02d2e6-9308-d242-9a4c-e2867df5c8d4"),
                            BirthDate = new DateTime(2023, 3, 13, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 8, 30, 20, 57, 44, 993, DateTimeKind.Local).AddTicks(6476),
                            CreatedBy = "Hardy_Hessel@gmail.com",
                            FirstName = "Eunice",
                            Gender = "Female",
                            LastName = "Mraz",
                            MiddleName = "팥୚᠀볦ꧦ㧋쵲蕦岰䳶",
                            Number = "ꕕ㑬亼ᷴ龿鞀㸫䍵",
                            Status = 0
                        },
                        new
                        {
                            Id = new Guid("502fa9b1-2780-1c20-a831-eadd602ac277"),
                            BirthDate = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            CreatedAt = new DateTime(2024, 7, 10, 7, 26, 4, 387, DateTimeKind.Local).AddTicks(4944),
                            CreatedBy = "Wilhelmine85@gmail.com",
                            FirstName = "Anita",
                            Gender = "Female",
                            LastName = "Franecki",
                            MiddleName = "鯥ॺɽ茖十㧕⇽艏앑鲒",
                            Number = "ަᴠ獦⭀꼣뮕ྜꖑ⒥",
                            Status = 2
                        });
                });

            modelBuilder.Entity("HRIS.Domain.Models.Entities.EmployeeVersion", b =>
                {
                    b.Property<DateTime>("Version")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Version");

                    b.ToTable("EmployeeVersions");
                });
#pragma warning restore 612, 618
        }
    }
}
